previewsEnabled: false

services:
- type: web
  name: central-login
  runtime: static
  rootDir: ./central-login
  buildCommand: npm run build
  staticPublishPath: ./dist
  buildFilter: 
    paths: 
      - '**/*.js'
      - '**/*.html'
      - '**/*.scss'
      - '**/*.css'
      - '**/*.json'

  envVars:
    - fromGroup: sample-settings

- type: web
  name: embedded-login
  runtime: static
  rootDir: ./embedded-login
  buildCommand: npm run build
  staticPublishPath: ./dist
  buildFilter: 
    paths: 
      - '**/*.js'
      - '**/*.html'
      - '**/*.scss'
      - '**/*.css'
      - '**/*.json'

  envVars:
    - fromGroup: sample-settings

- type: web
  name: angular-todo
  runtime: static
  rootDir: ./angular-todo
  staticPublishPath: ./dist/angular-todo/browser
  buildCommand: npm run build
  buildFilter: 
    paths: 
      - '**/*.js'
      - '**/*.ts'
      - '**/*.scss'
      - '**/*.css'
      - '**/*.html'
      - '**/*.json'
  envVars:
    - fromGroup: sample-settings

- type: web
  name: todo-api
  runtime: node
  rootDir: ./todo-api
  startCommand: node src/index.js
  buildCommand: npm ci
  buildFilter: 
    paths: 
      - '**/*.js'
      - '**/*.ts'
      - '**/*.json'
  envVars:
    - fromGroup: sample-settings

envVarGroups:
  - name: sample-settings
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: AM_URL
        sync: false

      - key: API_URL
        sync: false

      - key: JOURNEY_LOGIN
        sync: false

      - key: JOURNEY_REGISTER
        sync: false
      - key: PORT
        sync: false
      - key: WEB_OAUTH_CLIENT
        sync: false
      - key: WEB_OAUTH_CLIENT_SECRET
        sync: false
      - key: REALM_PATH
        sync: false
      - key: SCOPE
        sync: false
      - key: TIMEOUT
        sync: false
      - key: TREE
        sync: false