// Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
//
// This software may be modified and distributed under the terms
// of the MIT license. See the LICENSE file for details.
// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.pingidentity.flutter.journey

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Node type tag mirroring the native `Node` sealed hierarchy
 * (`ContinueNode`/`SuccessNode`/`ErrorNode`/`FailureNode`).
 */
enum class NodeType(val raw: Int) {
  CONTINUE_NODE(0),
  SUCCESS_NODE(1),
  ERROR_NODE(2),
  FAILURE_NODE(3);

  companion object {
    fun ofRaw(raw: Int): NodeType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Flat, wire-serializable Journey configuration. OIDC fields are hoisted to
 * the top level rather than nested, since Pigeon classes can't express an
 * "OIDC configured only if any OIDC field is present" union cleanly.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JourneyConfigMessage (
  val serverUrl: String,
  val realm: String? = null,
  val cookie: String? = null,
  /** Milliseconds. */
  val timeoutMillis: Long? = null,
  val clientId: String? = null,
  val discoveryEndpoint: String? = null,
  val redirectUri: String? = null,
  val scopes: List<String?>? = null,
  val acrValues: String? = null,
  val signOutRedirectUri: String? = null,
  val state: String? = null,
  val nonce: String? = null,
  val uiLocales: String? = null,
  /** Seconds. */
  val refreshThreshold: Long? = null,
  val loginHint: String? = null,
  val display: String? = null,
  val prompt: String? = null,
  val additionalParameters: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JourneyConfigMessage {
      val serverUrl = pigeonVar_list[0] as String
      val realm = pigeonVar_list[1] as String?
      val cookie = pigeonVar_list[2] as String?
      val timeoutMillis = pigeonVar_list[3] as Long?
      val clientId = pigeonVar_list[4] as String?
      val discoveryEndpoint = pigeonVar_list[5] as String?
      val redirectUri = pigeonVar_list[6] as String?
      val scopes = pigeonVar_list[7] as List<String?>?
      val acrValues = pigeonVar_list[8] as String?
      val signOutRedirectUri = pigeonVar_list[9] as String?
      val state = pigeonVar_list[10] as String?
      val nonce = pigeonVar_list[11] as String?
      val uiLocales = pigeonVar_list[12] as String?
      val refreshThreshold = pigeonVar_list[13] as Long?
      val loginHint = pigeonVar_list[14] as String?
      val display = pigeonVar_list[15] as String?
      val prompt = pigeonVar_list[16] as String?
      val additionalParameters = pigeonVar_list[17] as Map<String?, String?>?
      return JourneyConfigMessage(serverUrl, realm, cookie, timeoutMillis, clientId, discoveryEndpoint, redirectUri, scopes, acrValues, signOutRedirectUri, state, nonce, uiLocales, refreshThreshold, loginHint, display, prompt, additionalParameters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serverUrl,
      realm,
      cookie,
      timeoutMillis,
      clientId,
      discoveryEndpoint,
      redirectUri,
      scopes,
      acrValues,
      signOutRedirectUri,
      state,
      nonce,
      uiLocales,
      refreshThreshold,
      loginHint,
      display,
      prompt,
      additionalParameters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JourneyConfigMessage
    return MessagesPigeonUtils.deepEquals(this.serverUrl, other.serverUrl) && MessagesPigeonUtils.deepEquals(this.realm, other.realm) && MessagesPigeonUtils.deepEquals(this.cookie, other.cookie) && MessagesPigeonUtils.deepEquals(this.timeoutMillis, other.timeoutMillis) && MessagesPigeonUtils.deepEquals(this.clientId, other.clientId) && MessagesPigeonUtils.deepEquals(this.discoveryEndpoint, other.discoveryEndpoint) && MessagesPigeonUtils.deepEquals(this.redirectUri, other.redirectUri) && MessagesPigeonUtils.deepEquals(this.scopes, other.scopes) && MessagesPigeonUtils.deepEquals(this.acrValues, other.acrValues) && MessagesPigeonUtils.deepEquals(this.signOutRedirectUri, other.signOutRedirectUri) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.nonce, other.nonce) && MessagesPigeonUtils.deepEquals(this.uiLocales, other.uiLocales) && MessagesPigeonUtils.deepEquals(this.refreshThreshold, other.refreshThreshold) && MessagesPigeonUtils.deepEquals(this.loginHint, other.loginHint) && MessagesPigeonUtils.deepEquals(this.display, other.display) && MessagesPigeonUtils.deepEquals(this.prompt, other.prompt) && MessagesPigeonUtils.deepEquals(this.additionalParameters, other.additionalParameters)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serverUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.realm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cookie)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeoutMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.discoveryEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.redirectUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scopes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.acrValues)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.signOutRedirectUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nonce)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uiLocales)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.refreshThreshold)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.loginHint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.display)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prompt)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.additionalParameters)
    return result
  }
  override fun toString(): String {
    return "JourneyConfigMessage(serverUrl=$serverUrl, realm=$realm, cookie=$cookie, timeoutMillis=$timeoutMillis, clientId=$clientId, discoveryEndpoint=$discoveryEndpoint, redirectUri=$redirectUri, scopes=$scopes, acrValues=$acrValues, signOutRedirectUri=$signOutRedirectUri, state=$state, nonce=$nonce, uiLocales=$uiLocales, refreshThreshold=$refreshThreshold, loginHint=$loginHint, display=$display, prompt=$prompt, additionalParameters=$additionalParameters)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StartOptionsMessage (
  val forceAuth: Boolean,
  val noSession: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartOptionsMessage {
      val forceAuth = pigeonVar_list[0] as Boolean
      val noSession = pigeonVar_list[1] as Boolean
      return StartOptionsMessage(forceAuth, noSession)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      forceAuth,
      noSession,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StartOptionsMessage
    return MessagesPigeonUtils.deepEquals(this.forceAuth, other.forceAuth) && MessagesPigeonUtils.deepEquals(this.noSession, other.noSession)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.forceAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.noSession)
    return result
  }
  override fun toString(): String {
    return "StartOptionsMessage(forceAuth=$forceAuth, noSession=$noSession)"
  }
}

/**
 * Flat union of the v1 callback fields (~10 callback types). `value` is
 * `Object?`, StandardMessageCodec-backed (covers String/bool/num/Map/List).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CallbackMessage (
  val type: String,
  val index: Long,
  val prompt: String? = null,
  val message: String? = null,
  val required: Boolean? = null,
  val value: Any? = null,
  val choices: List<String?>? = null,
  val defaultChoice: Long? = null,
  val selectedIndex: Long? = null,
  /** Full terms-and-conditions text (TermsAndConditionsCallback). */
  val terms: String? = null,
  val version: String? = null,
  val createDate: String? = null,
  val accepted: Boolean? = null,
  /** Placeholder/default text (TextInputCallback). */
  val defaultText: String? = null,
  val predefinedQuestions: List<String?>? = null,
  val selectedQuestion: String? = null,
  val selectedAnswer: String? = null,
  val allowUserDefinedQuestions: Boolean? = null,
  /** Attribute name/label (Attribute*InputCallback), distinct from [value]. */
  val name: String? = null,
  /**
   * Validate-without-advancing flag (ValidatedUsername/ValidatedPassword/
   * Attribute*InputCallback). Read-only: reflects native state at mapping
   * time; [CallbackValueMessage] has no field to send an updated value back
   * to native (same limitation as the React Native bridge).
   */
  val validateOnly: Boolean? = null,
  val policies: Map<String?, Any?>? = null,
  /**
   * Each element is a `Map<String?, Object?>?`. Typed as `List<Object?>?` (rather than
   * `List<Map<String?, Object?>?>?`) because Pigeon's generated decoder does an unchecked
   * `.cast<Map<String?, Object?>?>()` on nested collection element types, which throws at
   * runtime the first time a real (non-empty) map element arrives over the wire — see
   * `NodeMapper._castFailedPolicies` for the safe elementwise cast this requires on read.
   */
  val failedPolicies: List<Any?>? = null,
  /** Whether to mask input (ValidatedPasswordCallback). */
  val echoOn: Boolean? = null,
  /** TextOutputCallback message classification: INFORMATION/WARNING/ERROR/SCRIPT/UNKNOWN. */
  val messageType: String? = null,
  val raw: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CallbackMessage {
      val type = pigeonVar_list[0] as String
      val index = pigeonVar_list[1] as Long
      val prompt = pigeonVar_list[2] as String?
      val message = pigeonVar_list[3] as String?
      val required = pigeonVar_list[4] as Boolean?
      val value = pigeonVar_list[5]
      val choices = pigeonVar_list[6] as List<String?>?
      val defaultChoice = pigeonVar_list[7] as Long?
      val selectedIndex = pigeonVar_list[8] as Long?
      val terms = pigeonVar_list[9] as String?
      val version = pigeonVar_list[10] as String?
      val createDate = pigeonVar_list[11] as String?
      val accepted = pigeonVar_list[12] as Boolean?
      val defaultText = pigeonVar_list[13] as String?
      val predefinedQuestions = pigeonVar_list[14] as List<String?>?
      val selectedQuestion = pigeonVar_list[15] as String?
      val selectedAnswer = pigeonVar_list[16] as String?
      val allowUserDefinedQuestions = pigeonVar_list[17] as Boolean?
      val name = pigeonVar_list[18] as String?
      val validateOnly = pigeonVar_list[19] as Boolean?
      val policies = pigeonVar_list[20] as Map<String?, Any?>?
      val failedPolicies = pigeonVar_list[21] as List<Any?>?
      val echoOn = pigeonVar_list[22] as Boolean?
      val messageType = pigeonVar_list[23] as String?
      val raw = pigeonVar_list[24] as Map<String?, Any?>?
      return CallbackMessage(type, index, prompt, message, required, value, choices, defaultChoice, selectedIndex, terms, version, createDate, accepted, defaultText, predefinedQuestions, selectedQuestion, selectedAnswer, allowUserDefinedQuestions, name, validateOnly, policies, failedPolicies, echoOn, messageType, raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      index,
      prompt,
      message,
      required,
      value,
      choices,
      defaultChoice,
      selectedIndex,
      terms,
      version,
      createDate,
      accepted,
      defaultText,
      predefinedQuestions,
      selectedQuestion,
      selectedAnswer,
      allowUserDefinedQuestions,
      name,
      validateOnly,
      policies,
      failedPolicies,
      echoOn,
      messageType,
      raw,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CallbackMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.index, other.index) && MessagesPigeonUtils.deepEquals(this.prompt, other.prompt) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.required, other.required) && MessagesPigeonUtils.deepEquals(this.value, other.value) && MessagesPigeonUtils.deepEquals(this.choices, other.choices) && MessagesPigeonUtils.deepEquals(this.defaultChoice, other.defaultChoice) && MessagesPigeonUtils.deepEquals(this.selectedIndex, other.selectedIndex) && MessagesPigeonUtils.deepEquals(this.terms, other.terms) && MessagesPigeonUtils.deepEquals(this.version, other.version) && MessagesPigeonUtils.deepEquals(this.createDate, other.createDate) && MessagesPigeonUtils.deepEquals(this.accepted, other.accepted) && MessagesPigeonUtils.deepEquals(this.defaultText, other.defaultText) && MessagesPigeonUtils.deepEquals(this.predefinedQuestions, other.predefinedQuestions) && MessagesPigeonUtils.deepEquals(this.selectedQuestion, other.selectedQuestion) && MessagesPigeonUtils.deepEquals(this.selectedAnswer, other.selectedAnswer) && MessagesPigeonUtils.deepEquals(this.allowUserDefinedQuestions, other.allowUserDefinedQuestions) && MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.validateOnly, other.validateOnly) && MessagesPigeonUtils.deepEquals(this.policies, other.policies) && MessagesPigeonUtils.deepEquals(this.failedPolicies, other.failedPolicies) && MessagesPigeonUtils.deepEquals(this.echoOn, other.echoOn) && MessagesPigeonUtils.deepEquals(this.messageType, other.messageType) && MessagesPigeonUtils.deepEquals(this.raw, other.raw)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.index)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prompt)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.required)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.choices)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.defaultChoice)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectedIndex)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.terms)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.version)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.createDate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accepted)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.defaultText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.predefinedQuestions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectedQuestion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectedAnswer)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.allowUserDefinedQuestions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.validateOnly)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.policies)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.failedPolicies)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.echoOn)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.messageType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.raw)
    return result
  }
  override fun toString(): String {
    return "CallbackMessage(type=$type, index=$index, prompt=$prompt, message=$message, required=$required, value=$value, choices=$choices, defaultChoice=$defaultChoice, selectedIndex=$selectedIndex, terms=$terms, version=$version, createDate=$createDate, accepted=$accepted, defaultText=$defaultText, predefinedQuestions=$predefinedQuestions, selectedQuestion=$selectedQuestion, selectedAnswer=$selectedAnswer, allowUserDefinedQuestions=$allowUserDefinedQuestions, name=$name, validateOnly=$validateOnly, policies=$policies, failedPolicies=$failedPolicies, echoOn=$echoOn, messageType=$messageType, raw=$raw)"
  }
}

/**
 * Dart -> native callback value, addressed by `{type, index}` so native can
 * re-resolve it against the cached `ContinueNode`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CallbackValueMessage (
  val type: String,
  val index: Long,
  val value: Any? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CallbackValueMessage {
      val type = pigeonVar_list[0] as String
      val index = pigeonVar_list[1] as Long
      val value = pigeonVar_list[2]
      return CallbackValueMessage(type, index, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      index,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CallbackValueMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.index, other.index) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.index)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
  override fun toString(): String {
    return "CallbackValueMessage(type=$type, index=$index, value=$value)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NodeMessage (
  val type: NodeType,
  val message: String? = null,
  val cause: String? = null,
  val status: Long? = null,
  /**
   * Page metadata (ContinueNode only) — native extension properties on
   * `ContinueNode`, exposed as real fields rather than left opaque.
   */
  val header: String? = null,
  val pageDescription: String? = null,
  val stage: String? = null,
  val callbacks: List<CallbackMessage?>? = null,
  val input: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NodeMessage {
      val type = pigeonVar_list[0] as NodeType
      val message = pigeonVar_list[1] as String?
      val cause = pigeonVar_list[2] as String?
      val status = pigeonVar_list[3] as Long?
      val header = pigeonVar_list[4] as String?
      val pageDescription = pigeonVar_list[5] as String?
      val stage = pigeonVar_list[6] as String?
      val callbacks = pigeonVar_list[7] as List<CallbackMessage?>?
      val input = pigeonVar_list[8] as Map<String?, Any?>?
      return NodeMessage(type, message, cause, status, header, pageDescription, stage, callbacks, input)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      message,
      cause,
      status,
      header,
      pageDescription,
      stage,
      callbacks,
      input,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NodeMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.cause, other.cause) && MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.header, other.header) && MessagesPigeonUtils.deepEquals(this.pageDescription, other.pageDescription) && MessagesPigeonUtils.deepEquals(this.stage, other.stage) && MessagesPigeonUtils.deepEquals(this.callbacks, other.callbacks) && MessagesPigeonUtils.deepEquals(this.input, other.input)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cause)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.header)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pageDescription)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.callbacks)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.input)
    return result
  }
  override fun toString(): String {
    return "NodeMessage(type=$type, message=$message, cause=$cause, status=$status, header=$header, pageDescription=$pageDescription, stage=$stage, callbacks=$callbacks, input=$input)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SessionMessage (
  val accessToken: String,
  val refreshToken: String? = null,
  val expiresIn: Long,
  val userInfo: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionMessage {
      val accessToken = pigeonVar_list[0] as String
      val refreshToken = pigeonVar_list[1] as String?
      val expiresIn = pigeonVar_list[2] as Long
      val userInfo = pigeonVar_list[3] as Map<String?, Any?>?
      return SessionMessage(accessToken, refreshToken, expiresIn, userInfo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessToken,
      refreshToken,
      expiresIn,
      userInfo,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SessionMessage
    return MessagesPigeonUtils.deepEquals(this.accessToken, other.accessToken) && MessagesPigeonUtils.deepEquals(this.refreshToken, other.refreshToken) && MessagesPigeonUtils.deepEquals(this.expiresIn, other.expiresIn) && MessagesPigeonUtils.deepEquals(this.userInfo, other.userInfo)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.refreshToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.expiresIn)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userInfo)
    return result
  }
  override fun toString(): String {
    return "SessionMessage(accessToken=$accessToken, refreshToken=$refreshToken, expiresIn=$expiresIn, userInfo=$userInfo)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NodeType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JourneyConfigMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartOptionsMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CallbackMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CallbackValueMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NodeMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NodeType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is JourneyConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is StartOptionsMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CallbackMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CallbackValueMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NodeMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SessionMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PingJourneyHostApi {
  fun configureJourney(config: JourneyConfigMessage, callback: (Result<String>) -> Unit)
  fun start(journeyId: String, name: String, options: StartOptionsMessage, callback: (Result<NodeMessage>) -> Unit)
  fun next(journeyId: String, values: List<CallbackValueMessage?>, callback: (Result<NodeMessage>) -> Unit)
  fun getSession(journeyId: String, callback: (Result<SessionMessage?>) -> Unit)
  fun signOff(journeyId: String, callback: (Result<Boolean>) -> Unit)
  fun dispose(journeyId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by PingJourneyHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PingJourneyHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PingJourneyHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.configureJourney$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as JourneyConfigMessage
            api.configureJourney(configArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val journeyIdArg = args[0] as String
            val nameArg = args[1] as String
            val optionsArg = args[2] as StartOptionsMessage
            api.start(journeyIdArg, nameArg, optionsArg) { result: Result<NodeMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.next$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val journeyIdArg = args[0] as String
            val valuesArg = args[1] as List<CallbackValueMessage?>
            api.next(journeyIdArg, valuesArg) { result: Result<NodeMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.getSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val journeyIdArg = args[0] as String
            api.getSession(journeyIdArg) { result: Result<SessionMessage?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.signOff$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val journeyIdArg = args[0] as String
            api.signOff(journeyIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val journeyIdArg = args[0] as String
            api.dispose(journeyIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
