// Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
//
// This software may be modified and distributed under the terms
// of the MIT license. See the LICENSE file for details.
// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum AuthorizeResultType {
  /// The user completed the browser login flow successfully.
  success,
  /// The user dismissed the browser without completing login. Not an error.
  cancel,
}

/// Explicit OpenID endpoint configuration — the "skip discovery" escape
/// hatch. Mirrors ping_core's `OidcOpenIdConfig` field-for-field.
class OidcOpenIdConfigMessage {
  OidcOpenIdConfigMessage({
    required this.authorizationEndpoint,
    required this.tokenEndpoint,
    required this.userinfoEndpoint,
    this.endSessionEndpoint,
    this.pingEndIdpSessionEndpoint,
    this.revocationEndpoint,
  });

  /// The authorization endpoint URL.
  String authorizationEndpoint;

  /// The token endpoint URL.
  String tokenEndpoint;

  /// The userinfo endpoint URL.
  String userinfoEndpoint;

  /// The end-session endpoint URL, if the provider supports RP-initiated logout.
  String? endSessionEndpoint;

  /// The Ping end-IDP-session endpoint URL, using just the id token.
  String? pingEndIdpSessionEndpoint;

  /// The token revocation endpoint URL.
  String? revocationEndpoint;

  List<Object?> _toList() {
    return <Object?>[
      authorizationEndpoint,
      tokenEndpoint,
      userinfoEndpoint,
      endSessionEndpoint,
      pingEndIdpSessionEndpoint,
      revocationEndpoint,
    ];
  }

  Object encode() {
    return _toList();  }

  static OidcOpenIdConfigMessage decode(Object result) {
    result as List<Object?>;
    return OidcOpenIdConfigMessage(
      authorizationEndpoint: result[0]! as String,
      tokenEndpoint: result[1]! as String,
      userinfoEndpoint: result[2]! as String,
      endSessionEndpoint: result[3] as String?,
      pingEndIdpSessionEndpoint: result[4] as String?,
      revocationEndpoint: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OidcOpenIdConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(authorizationEndpoint, other.authorizationEndpoint) && _deepEquals(tokenEndpoint, other.tokenEndpoint) && _deepEquals(userinfoEndpoint, other.userinfoEndpoint) && _deepEquals(endSessionEndpoint, other.endSessionEndpoint) && _deepEquals(pingEndIdpSessionEndpoint, other.pingEndIdpSessionEndpoint) && _deepEquals(revocationEndpoint, other.revocationEndpoint);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OidcOpenIdConfigMessage(authorizationEndpoint: $authorizationEndpoint, tokenEndpoint: $tokenEndpoint, userinfoEndpoint: $userinfoEndpoint, endSessionEndpoint: $endSessionEndpoint, pingEndIdpSessionEndpoint: $pingEndIdpSessionEndpoint, revocationEndpoint: $revocationEndpoint)';
  }
}

/// Flat, wire-serializable OIDC client configuration.
///
/// Neither [discoveryEndpoint] nor [openId] is required at the Pigeon-type
/// level — both native SDKs silently defer validation rather than throwing
/// if both are absent, so the bridge itself validates "at least one must be
/// present" in `OidcConfigParser` and throws a typed `OIDC_CONFIGURE_ERROR`.
class OidcConfigMessage {
  OidcConfigMessage({
    required this.clientId,
    required this.redirectUri,
    this.discoveryEndpoint,
    this.openId,
    this.scopes,
    this.acrValues,
    this.signOutRedirectUri,
    this.state,
    this.nonce,
    this.uiLocales,
    this.refreshThresholdSeconds,
    this.loginHint,
    this.display,
    this.prompt,
    this.additionalParameters,
    required this.par,
  });

  /// The OAuth2/OIDC client id.
  String clientId;

  /// The redirect URI registered for this client.
  String redirectUri;

  /// The discovery endpoint URL, if discovery is used instead of an explicit [openId].
  String? discoveryEndpoint;

  /// The explicit OpenID endpoint configuration, if discovery is not used.
  OidcOpenIdConfigMessage? openId;

  /// OAuth2 scopes requested during authorization.
  List<String?>? scopes;

  /// The `acr_values` authorization parameter.
  String? acrValues;

  /// Android-only at apply time — iOS's native `OidcClientConfig` has no
  /// such field.
  String? signOutRedirectUri;

  /// The `state` authorization parameter.
  String? state;

  /// The `nonce` authorization parameter.
  String? nonce;

  /// The `ui_locales` authorization parameter.
  String? uiLocales;

  /// Seconds. Named explicitly to avoid the Journey schema's units ambiguity.
  int? refreshThresholdSeconds;

  /// The `login_hint` authorization parameter.
  String? loginHint;

  /// The `display` authorization parameter.
  String? display;

  /// The `prompt` authorization parameter.
  String? prompt;

  /// Additional authorization parameters.
  Map<String?, String?>? additionalParameters;

  /// Whether to use Pushed Authorization Requests (RFC 9126).
  bool par;

  List<Object?> _toList() {
    return <Object?>[
      clientId,
      redirectUri,
      discoveryEndpoint,
      openId,
      scopes,
      acrValues,
      signOutRedirectUri,
      state,
      nonce,
      uiLocales,
      refreshThresholdSeconds,
      loginHint,
      display,
      prompt,
      additionalParameters,
      par,
    ];
  }

  Object encode() {
    return _toList();  }

  static OidcConfigMessage decode(Object result) {
    result as List<Object?>;
    return OidcConfigMessage(
      clientId: result[0]! as String,
      redirectUri: result[1]! as String,
      discoveryEndpoint: result[2] as String?,
      openId: result[3] as OidcOpenIdConfigMessage?,
      scopes: (result[4] as List<Object?>?)?.cast<String?>(),
      acrValues: result[5] as String?,
      signOutRedirectUri: result[6] as String?,
      state: result[7] as String?,
      nonce: result[8] as String?,
      uiLocales: result[9] as String?,
      refreshThresholdSeconds: result[10] as int?,
      loginHint: result[11] as String?,
      display: result[12] as String?,
      prompt: result[13] as String?,
      additionalParameters: (result[14] as Map<Object?, Object?>?)?.cast<String?, String?>(),
      par: result[15]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OidcConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clientId, other.clientId) && _deepEquals(redirectUri, other.redirectUri) && _deepEquals(discoveryEndpoint, other.discoveryEndpoint) && _deepEquals(openId, other.openId) && _deepEquals(scopes, other.scopes) && _deepEquals(acrValues, other.acrValues) && _deepEquals(signOutRedirectUri, other.signOutRedirectUri) && _deepEquals(state, other.state) && _deepEquals(nonce, other.nonce) && _deepEquals(uiLocales, other.uiLocales) && _deepEquals(refreshThresholdSeconds, other.refreshThresholdSeconds) && _deepEquals(loginHint, other.loginHint) && _deepEquals(display, other.display) && _deepEquals(prompt, other.prompt) && _deepEquals(additionalParameters, other.additionalParameters) && _deepEquals(par, other.par);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OidcConfigMessage(clientId: $clientId, redirectUri: $redirectUri, discoveryEndpoint: $discoveryEndpoint, openId: $openId, scopes: $scopes, acrValues: $acrValues, signOutRedirectUri: $signOutRedirectUri, state: $state, nonce: $nonce, uiLocales: $uiLocales, refreshThresholdSeconds: $refreshThresholdSeconds, loginHint: $loginHint, display: $display, prompt: $prompt, additionalParameters: $additionalParameters, par: $par)';
  }
}

/// iOS-only browser presentation knobs. Android ignores every field here —
/// it only has Chrome Custom Tabs, no `BrowserType`/`BrowserMode` equivalent.
class BrowserOptionsMessage {
  BrowserOptionsMessage({
    this.browserType,
    this.browserMode,
  });

  /// One of `authSession` / `ephemeralAuthSession` (both implemented on iOS
  /// at 2.1.0). `nativeBrowserApp` / `sfViewController` are declared but not
  /// implemented natively — the iOS bridge rejects them rather than passing
  /// through to a silent no-op.
  String? browserType;

  /// One of `login` / `logout` / `custom`.
  String? browserMode;

  List<Object?> _toList() {
    return <Object?>[
      browserType,
      browserMode,
    ];
  }

  Object encode() {
    return _toList();  }

  static BrowserOptionsMessage decode(Object result) {
    result as List<Object?>;
    return BrowserOptionsMessage(
      browserType: result[0] as String?,
      browserMode: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BrowserOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(browserType, other.browserType) && _deepEquals(browserMode, other.browserMode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BrowserOptionsMessage(browserType: $browserType, browserMode: $browserMode)';
  }
}

/// A minted OIDC token set. Deliberately excludes the expiry-stamp field
/// (`expireAt` on Android vs `expiresAt` on iOS diverge in both name and
/// visibility) — only `expiresIn` (present, public, on both) crosses the
/// bridge.
class TokenMessage {
  TokenMessage({
    required this.accessToken,
    this.tokenType,
    this.scope,
    required this.expiresIn,
    this.refreshToken,
    this.idToken,
  });

  /// The OAuth access token.
  String accessToken;

  /// The OAuth token type (e.g. `Bearer`), if the server returned one.
  String? tokenType;

  /// The granted scope string, if the server returned one.
  String? scope;

  /// The number of seconds until [accessToken] expires.
  int expiresIn;

  /// The OAuth refresh token, if the server returned one.
  String? refreshToken;

  /// The OIDC ID token, if the server returned one.
  String? idToken;

  List<Object?> _toList() {
    return <Object?>[
      accessToken,
      tokenType,
      scope,
      expiresIn,
      refreshToken,
      idToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static TokenMessage decode(Object result) {
    result as List<Object?>;
    return TokenMessage(
      accessToken: result[0]! as String,
      tokenType: result[1] as String?,
      scope: result[2] as String?,
      expiresIn: result[3]! as int,
      refreshToken: result[4] as String?,
      idToken: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TokenMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessToken, other.accessToken) && _deepEquals(tokenType, other.tokenType) && _deepEquals(scope, other.scope) && _deepEquals(expiresIn, other.expiresIn) && _deepEquals(refreshToken, other.refreshToken) && _deepEquals(idToken, other.idToken);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TokenMessage(accessToken: $accessToken, tokenType: $tokenType, scope: $scope, expiresIn: $expiresIn, refreshToken: $refreshToken, idToken: $idToken)';
  }
}

/// No authorization code, no `state`, no redirect URI ever crosses the
/// bridge — the native SDK captures the redirect and exchanges the code
/// internally on both platforms.
class AuthorizeResultMessage {
  AuthorizeResultMessage({
    required this.type,
  });

  /// Whether the browser flow completed successfully or was cancelled by the user.
  AuthorizeResultType type;

  List<Object?> _toList() {
    return <Object?>[
      type,
    ];
  }

  Object encode() {
    return _toList();  }

  static AuthorizeResultMessage decode(Object result) {
    result as List<Object?>;
    return AuthorizeResultMessage(
      type: result[0]! as AuthorizeResultType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthorizeResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AuthorizeResultMessage(type: $type)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AuthorizeResultType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is OidcOpenIdConfigMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is OidcConfigMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is BrowserOptionsMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is TokenMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is AuthorizeResultMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AuthorizeResultType.values[value];
      case 130:
        return OidcOpenIdConfigMessage.decode(readValue(buffer)!);
      case 131:
        return OidcConfigMessage.decode(readValue(buffer)!);
      case 132:
        return BrowserOptionsMessage.decode(readValue(buffer)!);
      case 133:
        return TokenMessage.decode(readValue(buffer)!);
      case 134:
        return AuthorizeResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PingOidcHostApi {
  /// Constructor for [PingOidcHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PingOidcHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Builds a native `OidcClient` for [config] and returns its handle id.
  Future<String> configureOidc(OidcConfigMessage config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.configureOidc$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// Builds a browser-capable `OidcWebClient` from the client identified by [clientId] and
  /// returns its handle id.
  Future<String> createWebClient(String clientId, BrowserOptionsMessage? options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.createWebClient$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[clientId, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// Opens the system browser for the user to authenticate.
  Future<AuthorizeResultMessage> authorize(String webClientId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.authorize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AuthorizeResultMessage;
  }

  /// Whether a signed-in user session already exists for this web client.
  Future<bool> hasUser(String webClientId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.hasUser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// The token most recently issued for this web client.
  Future<TokenMessage> token(String webClientId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.token$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as TokenMessage;
  }

  /// Forces a token refresh via the stored refresh token.
  Future<TokenMessage> refresh(String webClientId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.refresh$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as TokenMessage;
  }

  /// Fetches the userinfo claims for the signed-in user.
  Future<Map<String?, Object?>> userInfo(String webClientId, bool cache) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.userInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId, cache]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String?, Object?>();
  }

  /// Revokes the current token.
  Future<void> revoke(String webClientId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.revoke$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Signs the user out.
  Future<bool> signOff(String webClientId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.signOff$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[webClientId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Releases the native resources backing [handleId] (either a client or web-client handle).
  Future<void> dispose(String handleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_oidc.PingOidcHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
