// Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
//
// This software may be modified and distributed under the terms
// of the MIT license. See the LICENSE file for details.
// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Node type tag mirroring the native `Node` sealed hierarchy
/// (`ContinueNode`/`SuccessNode`/`ErrorNode`/`FailureNode`).
enum NodeType {
  continueNode,
  successNode,
  errorNode,
  failureNode,
}

/// Flat, wire-serializable Journey configuration. OIDC fields are hoisted to
/// the top level rather than nested, since Pigeon classes can't express an
/// "OIDC configured only if any OIDC field is present" union cleanly.
class JourneyConfigMessage {
  JourneyConfigMessage({
    required this.serverUrl,
    this.realm,
    this.cookie,
    this.timeoutMillis,
    this.clientId,
    this.discoveryEndpoint,
    this.redirectUri,
    this.scopes,
    this.acrValues,
    this.signOutRedirectUri,
    this.state,
    this.nonce,
    this.uiLocales,
    this.refreshThreshold,
    this.loginHint,
    this.display,
    this.prompt,
    this.additionalParameters,
  });

  String serverUrl;

  String? realm;

  String? cookie;

  /// Milliseconds.
  int? timeoutMillis;

  String? clientId;

  String? discoveryEndpoint;

  String? redirectUri;

  List<String?>? scopes;

  String? acrValues;

  String? signOutRedirectUri;

  String? state;

  String? nonce;

  String? uiLocales;

  /// Seconds.
  int? refreshThreshold;

  String? loginHint;

  String? display;

  String? prompt;

  Map<String?, String?>? additionalParameters;

  List<Object?> _toList() {
    return <Object?>[
      serverUrl,
      realm,
      cookie,
      timeoutMillis,
      clientId,
      discoveryEndpoint,
      redirectUri,
      scopes,
      acrValues,
      signOutRedirectUri,
      state,
      nonce,
      uiLocales,
      refreshThreshold,
      loginHint,
      display,
      prompt,
      additionalParameters,
    ];
  }

  Object encode() {
    return _toList();  }

  static JourneyConfigMessage decode(Object result) {
    result as List<Object?>;
    return JourneyConfigMessage(
      serverUrl: result[0]! as String,
      realm: result[1] as String?,
      cookie: result[2] as String?,
      timeoutMillis: result[3] as int?,
      clientId: result[4] as String?,
      discoveryEndpoint: result[5] as String?,
      redirectUri: result[6] as String?,
      scopes: (result[7] as List<Object?>?)?.cast<String?>(),
      acrValues: result[8] as String?,
      signOutRedirectUri: result[9] as String?,
      state: result[10] as String?,
      nonce: result[11] as String?,
      uiLocales: result[12] as String?,
      refreshThreshold: result[13] as int?,
      loginHint: result[14] as String?,
      display: result[15] as String?,
      prompt: result[16] as String?,
      additionalParameters: (result[17] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JourneyConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(serverUrl, other.serverUrl) && _deepEquals(realm, other.realm) && _deepEquals(cookie, other.cookie) && _deepEquals(timeoutMillis, other.timeoutMillis) && _deepEquals(clientId, other.clientId) && _deepEquals(discoveryEndpoint, other.discoveryEndpoint) && _deepEquals(redirectUri, other.redirectUri) && _deepEquals(scopes, other.scopes) && _deepEquals(acrValues, other.acrValues) && _deepEquals(signOutRedirectUri, other.signOutRedirectUri) && _deepEquals(state, other.state) && _deepEquals(nonce, other.nonce) && _deepEquals(uiLocales, other.uiLocales) && _deepEquals(refreshThreshold, other.refreshThreshold) && _deepEquals(loginHint, other.loginHint) && _deepEquals(display, other.display) && _deepEquals(prompt, other.prompt) && _deepEquals(additionalParameters, other.additionalParameters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'JourneyConfigMessage(serverUrl: $serverUrl, realm: $realm, cookie: $cookie, timeoutMillis: $timeoutMillis, clientId: $clientId, discoveryEndpoint: $discoveryEndpoint, redirectUri: $redirectUri, scopes: $scopes, acrValues: $acrValues, signOutRedirectUri: $signOutRedirectUri, state: $state, nonce: $nonce, uiLocales: $uiLocales, refreshThreshold: $refreshThreshold, loginHint: $loginHint, display: $display, prompt: $prompt, additionalParameters: $additionalParameters)';
  }
}

class StartOptionsMessage {
  StartOptionsMessage({
    required this.forceAuth,
    required this.noSession,
  });

  bool forceAuth;

  bool noSession;

  List<Object?> _toList() {
    return <Object?>[
      forceAuth,
      noSession,
    ];
  }

  Object encode() {
    return _toList();  }

  static StartOptionsMessage decode(Object result) {
    result as List<Object?>;
    return StartOptionsMessage(
      forceAuth: result[0]! as bool,
      noSession: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StartOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(forceAuth, other.forceAuth) && _deepEquals(noSession, other.noSession);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StartOptionsMessage(forceAuth: $forceAuth, noSession: $noSession)';
  }
}

/// Flat union of the v1 callback fields (~10 callback types). `value` is
/// `Object?`, StandardMessageCodec-backed (covers String/bool/num/Map/List).
class CallbackMessage {
  CallbackMessage({
    required this.type,
    required this.index,
    this.prompt,
    this.message,
    this.required,
    this.value,
    this.choices,
    this.defaultChoice,
    this.selectedIndex,
    this.terms,
    this.version,
    this.createDate,
    this.accepted,
    this.defaultText,
    this.predefinedQuestions,
    this.selectedQuestion,
    this.selectedAnswer,
    this.allowUserDefinedQuestions,
    this.name,
    this.validateOnly,
    this.policies,
    this.failedPolicies,
    this.echoOn,
    this.messageType,
    this.raw,
  });

  String type;

  int index;

  String? prompt;

  String? message;

  bool? required;

  Object? value;

  List<String?>? choices;

  int? defaultChoice;

  int? selectedIndex;

  /// Full terms-and-conditions text (TermsAndConditionsCallback).
  String? terms;

  String? version;

  String? createDate;

  bool? accepted;

  /// Placeholder/default text (TextInputCallback).
  String? defaultText;

  List<String?>? predefinedQuestions;

  String? selectedQuestion;

  String? selectedAnswer;

  bool? allowUserDefinedQuestions;

  /// Attribute name/label (Attribute*InputCallback), distinct from [value].
  String? name;

  /// Validate-without-advancing flag (ValidatedUsername/ValidatedPassword/
  /// Attribute*InputCallback).
  bool? validateOnly;

  Map<String?, Object?>? policies;

  List<Map<String?, Object?>?>? failedPolicies;

  /// Whether to mask input (ValidatedPasswordCallback).
  bool? echoOn;

  /// TextOutputCallback message classification: INFORMATION/WARNING/ERROR/SCRIPT/UNKNOWN.
  String? messageType;

  Map<String?, Object?>? raw;

  List<Object?> _toList() {
    return <Object?>[
      type,
      index,
      prompt,
      message,
      required,
      value,
      choices,
      defaultChoice,
      selectedIndex,
      terms,
      version,
      createDate,
      accepted,
      defaultText,
      predefinedQuestions,
      selectedQuestion,
      selectedAnswer,
      allowUserDefinedQuestions,
      name,
      validateOnly,
      policies,
      failedPolicies,
      echoOn,
      messageType,
      raw,
    ];
  }

  Object encode() {
    return _toList();  }

  static CallbackMessage decode(Object result) {
    result as List<Object?>;
    return CallbackMessage(
      type: result[0]! as String,
      index: result[1]! as int,
      prompt: result[2] as String?,
      message: result[3] as String?,
      required: result[4] as bool?,
      value: result[5],
      choices: (result[6] as List<Object?>?)?.cast<String?>(),
      defaultChoice: result[7] as int?,
      selectedIndex: result[8] as int?,
      terms: result[9] as String?,
      version: result[10] as String?,
      createDate: result[11] as String?,
      accepted: result[12] as bool?,
      defaultText: result[13] as String?,
      predefinedQuestions: (result[14] as List<Object?>?)?.cast<String?>(),
      selectedQuestion: result[15] as String?,
      selectedAnswer: result[16] as String?,
      allowUserDefinedQuestions: result[17] as bool?,
      name: result[18] as String?,
      validateOnly: result[19] as bool?,
      policies: (result[20] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      failedPolicies: (result[21] as List<Object?>?)?.cast<Map<String?, Object?>?>(),
      echoOn: result[22] as bool?,
      messageType: result[23] as String?,
      raw: (result[24] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CallbackMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(index, other.index) && _deepEquals(prompt, other.prompt) && _deepEquals(message, other.message) && _deepEquals(required, other.required) && _deepEquals(value, other.value) && _deepEquals(choices, other.choices) && _deepEquals(defaultChoice, other.defaultChoice) && _deepEquals(selectedIndex, other.selectedIndex) && _deepEquals(terms, other.terms) && _deepEquals(version, other.version) && _deepEquals(createDate, other.createDate) && _deepEquals(accepted, other.accepted) && _deepEquals(defaultText, other.defaultText) && _deepEquals(predefinedQuestions, other.predefinedQuestions) && _deepEquals(selectedQuestion, other.selectedQuestion) && _deepEquals(selectedAnswer, other.selectedAnswer) && _deepEquals(allowUserDefinedQuestions, other.allowUserDefinedQuestions) && _deepEquals(name, other.name) && _deepEquals(validateOnly, other.validateOnly) && _deepEquals(policies, other.policies) && _deepEquals(failedPolicies, other.failedPolicies) && _deepEquals(echoOn, other.echoOn) && _deepEquals(messageType, other.messageType) && _deepEquals(raw, other.raw);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CallbackMessage(type: $type, index: $index, prompt: $prompt, message: $message, required: $required, value: $value, choices: $choices, defaultChoice: $defaultChoice, selectedIndex: $selectedIndex, terms: $terms, version: $version, createDate: $createDate, accepted: $accepted, defaultText: $defaultText, predefinedQuestions: $predefinedQuestions, selectedQuestion: $selectedQuestion, selectedAnswer: $selectedAnswer, allowUserDefinedQuestions: $allowUserDefinedQuestions, name: $name, validateOnly: $validateOnly, policies: $policies, failedPolicies: $failedPolicies, echoOn: $echoOn, messageType: $messageType, raw: $raw)';
  }
}

/// Dart -> native callback value, addressed by `{type, index}` so native can
/// re-resolve it against the cached `ContinueNode`.
class CallbackValueMessage {
  CallbackValueMessage({
    required this.type,
    required this.index,
    this.value,
  });

  String type;

  int index;

  Object? value;

  List<Object?> _toList() {
    return <Object?>[
      type,
      index,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static CallbackValueMessage decode(Object result) {
    result as List<Object?>;
    return CallbackValueMessage(
      type: result[0]! as String,
      index: result[1]! as int,
      value: result[2],
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CallbackValueMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(index, other.index) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CallbackValueMessage(type: $type, index: $index, value: $value)';
  }
}

class NodeMessage {
  NodeMessage({
    required this.type,
    this.message,
    this.cause,
    this.status,
    this.header,
    this.pageDescription,
    this.stage,
    this.callbacks,
    this.input,
  });

  NodeType type;

  String? message;

  String? cause;

  int? status;

  /// Page metadata (ContinueNode only) — native extension properties on
  /// `ContinueNode`, exposed as real fields rather than left opaque.
  String? header;

  String? pageDescription;

  String? stage;

  List<CallbackMessage?>? callbacks;

  Map<String?, Object?>? input;

  List<Object?> _toList() {
    return <Object?>[
      type,
      message,
      cause,
      status,
      header,
      pageDescription,
      stage,
      callbacks,
      input,
    ];
  }

  Object encode() {
    return _toList();  }

  static NodeMessage decode(Object result) {
    result as List<Object?>;
    return NodeMessage(
      type: result[0]! as NodeType,
      message: result[1] as String?,
      cause: result[2] as String?,
      status: result[3] as int?,
      header: result[4] as String?,
      pageDescription: result[5] as String?,
      stage: result[6] as String?,
      callbacks: (result[7] as List<Object?>?)?.cast<CallbackMessage?>(),
      input: (result[8] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NodeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(message, other.message) && _deepEquals(cause, other.cause) && _deepEquals(status, other.status) && _deepEquals(header, other.header) && _deepEquals(pageDescription, other.pageDescription) && _deepEquals(stage, other.stage) && _deepEquals(callbacks, other.callbacks) && _deepEquals(input, other.input);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NodeMessage(type: $type, message: $message, cause: $cause, status: $status, header: $header, pageDescription: $pageDescription, stage: $stage, callbacks: $callbacks, input: $input)';
  }
}

class SessionMessage {
  SessionMessage({
    required this.accessToken,
    this.refreshToken,
    required this.expiresIn,
    this.userInfo,
  });

  String accessToken;

  String? refreshToken;

  int expiresIn;

  Map<String?, Object?>? userInfo;

  List<Object?> _toList() {
    return <Object?>[
      accessToken,
      refreshToken,
      expiresIn,
      userInfo,
    ];
  }

  Object encode() {
    return _toList();  }

  static SessionMessage decode(Object result) {
    result as List<Object?>;
    return SessionMessage(
      accessToken: result[0]! as String,
      refreshToken: result[1] as String?,
      expiresIn: result[2]! as int,
      userInfo: (result[3] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessToken, other.accessToken) && _deepEquals(refreshToken, other.refreshToken) && _deepEquals(expiresIn, other.expiresIn) && _deepEquals(userInfo, other.userInfo);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionMessage(accessToken: $accessToken, refreshToken: $refreshToken, expiresIn: $expiresIn, userInfo: $userInfo)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NodeType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is JourneyConfigMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is StartOptionsMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CallbackMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CallbackValueMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NodeMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is SessionMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NodeType.values[value];
      case 130:
        return JourneyConfigMessage.decode(readValue(buffer)!);
      case 131:
        return StartOptionsMessage.decode(readValue(buffer)!);
      case 132:
        return CallbackMessage.decode(readValue(buffer)!);
      case 133:
        return CallbackValueMessage.decode(readValue(buffer)!);
      case 134:
        return NodeMessage.decode(readValue(buffer)!);
      case 135:
        return SessionMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PingJourneyHostApi {
  /// Constructor for [PingJourneyHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PingJourneyHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> configureJourney(JourneyConfigMessage config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_journey.PingJourneyHostApi.configureJourney$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<NodeMessage> start(String journeyId, String name, StartOptionsMessage options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_journey.PingJourneyHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[journeyId, name, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NodeMessage;
  }

  Future<NodeMessage> next(String journeyId, List<CallbackValueMessage?> values) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_journey.PingJourneyHostApi.next$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[journeyId, values]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NodeMessage;
  }

  Future<SessionMessage?> getSession(String journeyId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_journey.PingJourneyHostApi.getSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[journeyId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as SessionMessage?;
  }

  Future<bool> signOff(String journeyId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_journey.PingJourneyHostApi.signOff$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[journeyId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> dispose(String journeyId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ping_journey.PingJourneyHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[journeyId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
