// Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
//
// This software may be modified and distributed under the terms
// of the MIT license. See the LICENSE file for details.
// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Node type tag mirroring the native `Node` sealed hierarchy
/// (`ContinueNode`/`SuccessNode`/`ErrorNode`/`FailureNode`).
enum NodeType: Int, CaseIterable {
  case continueNode = 0
  case successNode = 1
  case errorNode = 2
  case failureNode = 3
}

/// Flat, wire-serializable Journey configuration. OIDC fields are hoisted to
/// the top level rather than nested, since Pigeon classes can't express an
/// "OIDC configured only if any OIDC field is present" union cleanly.
///
/// Generated class from Pigeon that represents data sent in messages.
struct JourneyConfigMessage: Hashable, CustomStringConvertible {
  var serverUrl: String
  var realm: String? = nil
  var cookie: String? = nil
  /// Milliseconds.
  var timeoutMillis: Int64? = nil
  var clientId: String? = nil
  var discoveryEndpoint: String? = nil
  var redirectUri: String? = nil
  var scopes: [String?]? = nil
  var acrValues: String? = nil
  var signOutRedirectUri: String? = nil
  var state: String? = nil
  var nonce: String? = nil
  var uiLocales: String? = nil
  /// Seconds.
  var refreshThreshold: Int64? = nil
  var loginHint: String? = nil
  var display: String? = nil
  var prompt: String? = nil
  var additionalParameters: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> JourneyConfigMessage? {
    let serverUrl = pigeonVar_list[0] as! String
    let realm: String? = nilOrValue(pigeonVar_list[1])
    let cookie: String? = nilOrValue(pigeonVar_list[2])
    let timeoutMillis: Int64? = nilOrValue(pigeonVar_list[3])
    let clientId: String? = nilOrValue(pigeonVar_list[4])
    let discoveryEndpoint: String? = nilOrValue(pigeonVar_list[5])
    let redirectUri: String? = nilOrValue(pigeonVar_list[6])
    let scopes: [String?]? = nilOrValue(pigeonVar_list[7])
    let acrValues: String? = nilOrValue(pigeonVar_list[8])
    let signOutRedirectUri: String? = nilOrValue(pigeonVar_list[9])
    let state: String? = nilOrValue(pigeonVar_list[10])
    let nonce: String? = nilOrValue(pigeonVar_list[11])
    let uiLocales: String? = nilOrValue(pigeonVar_list[12])
    let refreshThreshold: Int64? = nilOrValue(pigeonVar_list[13])
    let loginHint: String? = nilOrValue(pigeonVar_list[14])
    let display: String? = nilOrValue(pigeonVar_list[15])
    let prompt: String? = nilOrValue(pigeonVar_list[16])
    let additionalParameters: [String?: String?]? = nilOrValue(pigeonVar_list[17])

    return JourneyConfigMessage(
      serverUrl: serverUrl,
      realm: realm,
      cookie: cookie,
      timeoutMillis: timeoutMillis,
      clientId: clientId,
      discoveryEndpoint: discoveryEndpoint,
      redirectUri: redirectUri,
      scopes: scopes,
      acrValues: acrValues,
      signOutRedirectUri: signOutRedirectUri,
      state: state,
      nonce: nonce,
      uiLocales: uiLocales,
      refreshThreshold: refreshThreshold,
      loginHint: loginHint,
      display: display,
      prompt: prompt,
      additionalParameters: additionalParameters
    )
  }
  func toList() -> [Any?] {
    return [
      serverUrl,
      realm,
      cookie,
      timeoutMillis,
      clientId,
      discoveryEndpoint,
      redirectUri,
      scopes,
      acrValues,
      signOutRedirectUri,
      state,
      nonce,
      uiLocales,
      refreshThreshold,
      loginHint,
      display,
      prompt,
      additionalParameters,
    ]
  }
  static func == (lhs: JourneyConfigMessage, rhs: JourneyConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.serverUrl, rhs.serverUrl) && MessagesPigeonInternal.deepEquals(lhs.realm, rhs.realm) && MessagesPigeonInternal.deepEquals(lhs.cookie, rhs.cookie) && MessagesPigeonInternal.deepEquals(lhs.timeoutMillis, rhs.timeoutMillis) && MessagesPigeonInternal.deepEquals(lhs.clientId, rhs.clientId) && MessagesPigeonInternal.deepEquals(lhs.discoveryEndpoint, rhs.discoveryEndpoint) && MessagesPigeonInternal.deepEquals(lhs.redirectUri, rhs.redirectUri) && MessagesPigeonInternal.deepEquals(lhs.scopes, rhs.scopes) && MessagesPigeonInternal.deepEquals(lhs.acrValues, rhs.acrValues) && MessagesPigeonInternal.deepEquals(lhs.signOutRedirectUri, rhs.signOutRedirectUri) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.nonce, rhs.nonce) && MessagesPigeonInternal.deepEquals(lhs.uiLocales, rhs.uiLocales) && MessagesPigeonInternal.deepEquals(lhs.refreshThreshold, rhs.refreshThreshold) && MessagesPigeonInternal.deepEquals(lhs.loginHint, rhs.loginHint) && MessagesPigeonInternal.deepEquals(lhs.display, rhs.display) && MessagesPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && MessagesPigeonInternal.deepEquals(lhs.additionalParameters, rhs.additionalParameters)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("JourneyConfigMessage")
    MessagesPigeonInternal.deepHash(value: serverUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: realm, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cookie, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timeoutMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: clientId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: discoveryEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: redirectUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scopes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: acrValues, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: signOutRedirectUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nonce, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uiLocales, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: refreshThreshold, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: loginHint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: display, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: additionalParameters, hasher: &hasher)
  }

  public var description: String {
    return "JourneyConfigMessage(serverUrl: \(String(describing: serverUrl)), realm: \(String(describing: realm)), cookie: \(String(describing: cookie)), timeoutMillis: \(String(describing: timeoutMillis)), clientId: \(String(describing: clientId)), discoveryEndpoint: \(String(describing: discoveryEndpoint)), redirectUri: \(String(describing: redirectUri)), scopes: \(String(describing: scopes)), acrValues: \(String(describing: acrValues)), signOutRedirectUri: \(String(describing: signOutRedirectUri)), state: \(String(describing: state)), nonce: \(String(describing: nonce)), uiLocales: \(String(describing: uiLocales)), refreshThreshold: \(String(describing: refreshThreshold)), loginHint: \(String(describing: loginHint)), display: \(String(describing: display)), prompt: \(String(describing: prompt)), additionalParameters: \(String(describing: additionalParameters)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StartOptionsMessage: Hashable, CustomStringConvertible {
  var forceAuth: Bool
  var noSession: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartOptionsMessage? {
    let forceAuth = pigeonVar_list[0] as! Bool
    let noSession = pigeonVar_list[1] as! Bool

    return StartOptionsMessage(
      forceAuth: forceAuth,
      noSession: noSession
    )
  }
  func toList() -> [Any?] {
    return [
      forceAuth,
      noSession,
    ]
  }
  static func == (lhs: StartOptionsMessage, rhs: StartOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.forceAuth, rhs.forceAuth) && MessagesPigeonInternal.deepEquals(lhs.noSession, rhs.noSession)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StartOptionsMessage")
    MessagesPigeonInternal.deepHash(value: forceAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: noSession, hasher: &hasher)
  }

  public var description: String {
    return "StartOptionsMessage(forceAuth: \(String(describing: forceAuth)), noSession: \(String(describing: noSession)))"
  }
}

/// Flat union of the v1 callback fields (~10 callback types). `value` is
/// `Object?`, StandardMessageCodec-backed (covers String/bool/num/Map/List).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CallbackMessage: Hashable, CustomStringConvertible {
  var type: String
  var index: Int64
  var prompt: String? = nil
  var message: String? = nil
  var required: Bool? = nil
  var value: Any? = nil
  var choices: [String?]? = nil
  var defaultChoice: Int64? = nil
  var selectedIndex: Int64? = nil
  /// Full terms-and-conditions text (TermsAndConditionsCallback).
  var terms: String? = nil
  var version: String? = nil
  var createDate: String? = nil
  var accepted: Bool? = nil
  /// Placeholder/default text (TextInputCallback).
  var defaultText: String? = nil
  var predefinedQuestions: [String?]? = nil
  var selectedQuestion: String? = nil
  var selectedAnswer: String? = nil
  var allowUserDefinedQuestions: Bool? = nil
  /// Attribute name/label (Attribute*InputCallback), distinct from [value].
  var name: String? = nil
  /// Validate-without-advancing flag (ValidatedUsername/ValidatedPassword/
  /// Attribute*InputCallback). Read-only: reflects native state at mapping
  /// time; [CallbackValueMessage] has no field to send an updated value back
  /// to native (same limitation as the React Native bridge).
  var validateOnly: Bool? = nil
  var policies: [String?: Any?]? = nil
  /// Each element is a `Map<String?, Object?>?`. Typed as `List<Object?>?` (rather than
  /// `List<Map<String?, Object?>?>?`) because Pigeon's generated decoder does an unchecked
  /// `.cast<Map<String?, Object?>?>()` on nested collection element types, which throws at
  /// runtime the first time a real (non-empty) map element arrives over the wire — see
  /// `NodeMapper._castFailedPolicies` for the safe elementwise cast this requires on read.
  var failedPolicies: [Any?]? = nil
  /// Whether to mask input (ValidatedPasswordCallback).
  var echoOn: Bool? = nil
  /// TextOutputCallback message classification: INFORMATION/WARNING/ERROR/SCRIPT/UNKNOWN.
  var messageType: String? = nil
  var raw: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CallbackMessage? {
    let type = pigeonVar_list[0] as! String
    let index = pigeonVar_list[1] as! Int64
    let prompt: String? = nilOrValue(pigeonVar_list[2])
    let message: String? = nilOrValue(pigeonVar_list[3])
    let required: Bool? = nilOrValue(pigeonVar_list[4])
    let value: Any? = pigeonVar_list[5]
    let choices: [String?]? = nilOrValue(pigeonVar_list[6])
    let defaultChoice: Int64? = nilOrValue(pigeonVar_list[7])
    let selectedIndex: Int64? = nilOrValue(pigeonVar_list[8])
    let terms: String? = nilOrValue(pigeonVar_list[9])
    let version: String? = nilOrValue(pigeonVar_list[10])
    let createDate: String? = nilOrValue(pigeonVar_list[11])
    let accepted: Bool? = nilOrValue(pigeonVar_list[12])
    let defaultText: String? = nilOrValue(pigeonVar_list[13])
    let predefinedQuestions: [String?]? = nilOrValue(pigeonVar_list[14])
    let selectedQuestion: String? = nilOrValue(pigeonVar_list[15])
    let selectedAnswer: String? = nilOrValue(pigeonVar_list[16])
    let allowUserDefinedQuestions: Bool? = nilOrValue(pigeonVar_list[17])
    let name: String? = nilOrValue(pigeonVar_list[18])
    let validateOnly: Bool? = nilOrValue(pigeonVar_list[19])
    let policies: [String?: Any?]? = nilOrValue(pigeonVar_list[20])
    let failedPolicies: [Any?]? = nilOrValue(pigeonVar_list[21])
    let echoOn: Bool? = nilOrValue(pigeonVar_list[22])
    let messageType: String? = nilOrValue(pigeonVar_list[23])
    let raw: [String?: Any?]? = nilOrValue(pigeonVar_list[24])

    return CallbackMessage(
      type: type,
      index: index,
      prompt: prompt,
      message: message,
      required: required,
      value: value,
      choices: choices,
      defaultChoice: defaultChoice,
      selectedIndex: selectedIndex,
      terms: terms,
      version: version,
      createDate: createDate,
      accepted: accepted,
      defaultText: defaultText,
      predefinedQuestions: predefinedQuestions,
      selectedQuestion: selectedQuestion,
      selectedAnswer: selectedAnswer,
      allowUserDefinedQuestions: allowUserDefinedQuestions,
      name: name,
      validateOnly: validateOnly,
      policies: policies,
      failedPolicies: failedPolicies,
      echoOn: echoOn,
      messageType: messageType,
      raw: raw
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      index,
      prompt,
      message,
      required,
      value,
      choices,
      defaultChoice,
      selectedIndex,
      terms,
      version,
      createDate,
      accepted,
      defaultText,
      predefinedQuestions,
      selectedQuestion,
      selectedAnswer,
      allowUserDefinedQuestions,
      name,
      validateOnly,
      policies,
      failedPolicies,
      echoOn,
      messageType,
      raw,
    ]
  }
  static func == (lhs: CallbackMessage, rhs: CallbackMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.index, rhs.index) && MessagesPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.required, rhs.required) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value) && MessagesPigeonInternal.deepEquals(lhs.choices, rhs.choices) && MessagesPigeonInternal.deepEquals(lhs.defaultChoice, rhs.defaultChoice) && MessagesPigeonInternal.deepEquals(lhs.selectedIndex, rhs.selectedIndex) && MessagesPigeonInternal.deepEquals(lhs.terms, rhs.terms) && MessagesPigeonInternal.deepEquals(lhs.version, rhs.version) && MessagesPigeonInternal.deepEquals(lhs.createDate, rhs.createDate) && MessagesPigeonInternal.deepEquals(lhs.accepted, rhs.accepted) && MessagesPigeonInternal.deepEquals(lhs.defaultText, rhs.defaultText) && MessagesPigeonInternal.deepEquals(lhs.predefinedQuestions, rhs.predefinedQuestions) && MessagesPigeonInternal.deepEquals(lhs.selectedQuestion, rhs.selectedQuestion) && MessagesPigeonInternal.deepEquals(lhs.selectedAnswer, rhs.selectedAnswer) && MessagesPigeonInternal.deepEquals(lhs.allowUserDefinedQuestions, rhs.allowUserDefinedQuestions) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.validateOnly, rhs.validateOnly) && MessagesPigeonInternal.deepEquals(lhs.policies, rhs.policies) && MessagesPigeonInternal.deepEquals(lhs.failedPolicies, rhs.failedPolicies) && MessagesPigeonInternal.deepEquals(lhs.echoOn, rhs.echoOn) && MessagesPigeonInternal.deepEquals(lhs.messageType, rhs.messageType) && MessagesPigeonInternal.deepEquals(lhs.raw, rhs.raw)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CallbackMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: index, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: required, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: choices, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: defaultChoice, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selectedIndex, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: terms, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: version, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: createDate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: accepted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: defaultText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: predefinedQuestions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selectedQuestion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selectedAnswer, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: allowUserDefinedQuestions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: validateOnly, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: policies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: failedPolicies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: echoOn, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: messageType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: raw, hasher: &hasher)
  }

  public var description: String {
    return "CallbackMessage(type: \(String(describing: type)), index: \(String(describing: index)), prompt: \(String(describing: prompt)), message: \(String(describing: message)), required: \(String(describing: required)), value: \(String(describing: value)), choices: \(String(describing: choices)), defaultChoice: \(String(describing: defaultChoice)), selectedIndex: \(String(describing: selectedIndex)), terms: \(String(describing: terms)), version: \(String(describing: version)), createDate: \(String(describing: createDate)), accepted: \(String(describing: accepted)), defaultText: \(String(describing: defaultText)), predefinedQuestions: \(String(describing: predefinedQuestions)), selectedQuestion: \(String(describing: selectedQuestion)), selectedAnswer: \(String(describing: selectedAnswer)), allowUserDefinedQuestions: \(String(describing: allowUserDefinedQuestions)), name: \(String(describing: name)), validateOnly: \(String(describing: validateOnly)), policies: \(String(describing: policies)), failedPolicies: \(String(describing: failedPolicies)), echoOn: \(String(describing: echoOn)), messageType: \(String(describing: messageType)), raw: \(String(describing: raw)))"
  }
}

/// Dart -> native callback value, addressed by `{type, index}` so native can
/// re-resolve it against the cached `ContinueNode`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CallbackValueMessage: Hashable, CustomStringConvertible {
  var type: String
  var index: Int64
  var value: Any? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CallbackValueMessage? {
    let type = pigeonVar_list[0] as! String
    let index = pigeonVar_list[1] as! Int64
    let value: Any? = pigeonVar_list[2]

    return CallbackValueMessage(
      type: type,
      index: index,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      index,
      value,
    ]
  }
  static func == (lhs: CallbackValueMessage, rhs: CallbackValueMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.index, rhs.index) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CallbackValueMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: index, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "CallbackValueMessage(type: \(String(describing: type)), index: \(String(describing: index)), value: \(String(describing: value)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NodeMessage: Hashable, CustomStringConvertible {
  var type: NodeType
  var message: String? = nil
  var cause: String? = nil
  var status: Int64? = nil
  /// Page metadata (ContinueNode only) — native extension properties on
  /// `ContinueNode`, exposed as real fields rather than left opaque.
  var header: String? = nil
  var pageDescription: String? = nil
  var stage: String? = nil
  var callbacks: [CallbackMessage?]? = nil
  var input: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NodeMessage? {
    let type = pigeonVar_list[0] as! NodeType
    let message: String? = nilOrValue(pigeonVar_list[1])
    let cause: String? = nilOrValue(pigeonVar_list[2])
    let status: Int64? = nilOrValue(pigeonVar_list[3])
    let header: String? = nilOrValue(pigeonVar_list[4])
    let pageDescription: String? = nilOrValue(pigeonVar_list[5])
    let stage: String? = nilOrValue(pigeonVar_list[6])
    let callbacks: [CallbackMessage?]? = nilOrValue(pigeonVar_list[7])
    let input: [String?: Any?]? = nilOrValue(pigeonVar_list[8])

    return NodeMessage(
      type: type,
      message: message,
      cause: cause,
      status: status,
      header: header,
      pageDescription: pageDescription,
      stage: stage,
      callbacks: callbacks,
      input: input
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      message,
      cause,
      status,
      header,
      pageDescription,
      stage,
      callbacks,
      input,
    ]
  }
  static func == (lhs: NodeMessage, rhs: NodeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.cause, rhs.cause) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.header, rhs.header) && MessagesPigeonInternal.deepEquals(lhs.pageDescription, rhs.pageDescription) && MessagesPigeonInternal.deepEquals(lhs.stage, rhs.stage) && MessagesPigeonInternal.deepEquals(lhs.callbacks, rhs.callbacks) && MessagesPigeonInternal.deepEquals(lhs.input, rhs.input)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NodeMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cause, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: header, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pageDescription, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: callbacks, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: input, hasher: &hasher)
  }

  public var description: String {
    return "NodeMessage(type: \(String(describing: type)), message: \(String(describing: message)), cause: \(String(describing: cause)), status: \(String(describing: status)), header: \(String(describing: header)), pageDescription: \(String(describing: pageDescription)), stage: \(String(describing: stage)), callbacks: \(String(describing: callbacks)), input: \(String(describing: input)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionMessage: Hashable, CustomStringConvertible {
  var accessToken: String
  var refreshToken: String? = nil
  var expiresIn: Int64
  var userInfo: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionMessage? {
    let accessToken = pigeonVar_list[0] as! String
    let refreshToken: String? = nilOrValue(pigeonVar_list[1])
    let expiresIn = pigeonVar_list[2] as! Int64
    let userInfo: [String?: Any?]? = nilOrValue(pigeonVar_list[3])

    return SessionMessage(
      accessToken: accessToken,
      refreshToken: refreshToken,
      expiresIn: expiresIn,
      userInfo: userInfo
    )
  }
  func toList() -> [Any?] {
    return [
      accessToken,
      refreshToken,
      expiresIn,
      userInfo,
    ]
  }
  static func == (lhs: SessionMessage, rhs: SessionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.accessToken, rhs.accessToken) && MessagesPigeonInternal.deepEquals(lhs.refreshToken, rhs.refreshToken) && MessagesPigeonInternal.deepEquals(lhs.expiresIn, rhs.expiresIn) && MessagesPigeonInternal.deepEquals(lhs.userInfo, rhs.userInfo)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SessionMessage")
    MessagesPigeonInternal.deepHash(value: accessToken, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: refreshToken, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expiresIn, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userInfo, hasher: &hasher)
  }

  public var description: String {
    return "SessionMessage(accessToken: \(String(describing: accessToken)), refreshToken: \(String(describing: refreshToken)), expiresIn: \(String(describing: expiresIn)), userInfo: \(String(describing: userInfo)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NodeType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return JourneyConfigMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return StartOptionsMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return CallbackMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return CallbackValueMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return NodeMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return SessionMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NodeType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? JourneyConfigMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? StartOptionsMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CallbackMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CallbackValueMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NodeMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? SessionMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PingJourneyHostApi {
  func configureJourney(config: JourneyConfigMessage, completion: @escaping (Result<String, Error>) -> Void)
  func start(journeyId: String, name: String, options: StartOptionsMessage, completion: @escaping (Result<NodeMessage, Error>) -> Void)
  func next(journeyId: String, values: [CallbackValueMessage?], completion: @escaping (Result<NodeMessage, Error>) -> Void)
  func getSession(journeyId: String, completion: @escaping (Result<SessionMessage?, Error>) -> Void)
  func signOff(journeyId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func dispose(journeyId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PingJourneyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PingJourneyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PingJourneyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureJourneyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.configureJourney\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureJourneyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! JourneyConfigMessage
        api.configureJourney(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureJourneyChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let journeyIdArg = args[0] as! String
        let nameArg = args[1] as! String
        let optionsArg = args[2] as! StartOptionsMessage
        api.start(journeyId: journeyIdArg, name: nameArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let nextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.next\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      nextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let journeyIdArg = args[0] as! String
        let valuesArg = args[1] as! [CallbackValueMessage?]
        api.next(journeyId: journeyIdArg, values: valuesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      nextChannel.setMessageHandler(nil)
    }
    let getSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.getSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let journeyIdArg = args[0] as! String
        api.getSession(journeyId: journeyIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSessionChannel.setMessageHandler(nil)
    }
    let signOffChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.signOff\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signOffChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let journeyIdArg = args[0] as! String
        api.signOff(journeyId: journeyIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signOffChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_journey.PingJourneyHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let journeyIdArg = args[0] as! String
        api.dispose(journeyId: journeyIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
