// Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
//
// This software may be modified and distributed under the terms
// of the MIT license. See the LICENSE file for details.
// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum AuthorizeResultType: Int, CaseIterable {
  /// The user completed the browser login flow successfully.
  case success = 0
  /// The user dismissed the browser without completing login. Not an error.
  case cancel = 1
}

/// Explicit OpenID endpoint configuration — the "skip discovery" escape
/// hatch. Mirrors ping_core's `OidcOpenIdConfig` field-for-field.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OidcOpenIdConfigMessage: Hashable, CustomStringConvertible {
  /// The authorization endpoint URL.
  var authorizationEndpoint: String
  /// The token endpoint URL.
  var tokenEndpoint: String
  /// The userinfo endpoint URL.
  var userinfoEndpoint: String
  /// The end-session endpoint URL, if the provider supports RP-initiated logout.
  var endSessionEndpoint: String? = nil
  /// The Ping end-IDP-session endpoint URL, using just the id token.
  var pingEndIdpSessionEndpoint: String? = nil
  /// The token revocation endpoint URL.
  var revocationEndpoint: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OidcOpenIdConfigMessage? {
    let authorizationEndpoint = pigeonVar_list[0] as! String
    let tokenEndpoint = pigeonVar_list[1] as! String
    let userinfoEndpoint = pigeonVar_list[2] as! String
    let endSessionEndpoint: String? = nilOrValue(pigeonVar_list[3])
    let pingEndIdpSessionEndpoint: String? = nilOrValue(pigeonVar_list[4])
    let revocationEndpoint: String? = nilOrValue(pigeonVar_list[5])

    return OidcOpenIdConfigMessage(
      authorizationEndpoint: authorizationEndpoint,
      tokenEndpoint: tokenEndpoint,
      userinfoEndpoint: userinfoEndpoint,
      endSessionEndpoint: endSessionEndpoint,
      pingEndIdpSessionEndpoint: pingEndIdpSessionEndpoint,
      revocationEndpoint: revocationEndpoint
    )
  }
  func toList() -> [Any?] {
    return [
      authorizationEndpoint,
      tokenEndpoint,
      userinfoEndpoint,
      endSessionEndpoint,
      pingEndIdpSessionEndpoint,
      revocationEndpoint,
    ]
  }
  static func == (lhs: OidcOpenIdConfigMessage, rhs: OidcOpenIdConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.authorizationEndpoint, rhs.authorizationEndpoint) && MessagesPigeonInternal.deepEquals(lhs.tokenEndpoint, rhs.tokenEndpoint) && MessagesPigeonInternal.deepEquals(lhs.userinfoEndpoint, rhs.userinfoEndpoint) && MessagesPigeonInternal.deepEquals(lhs.endSessionEndpoint, rhs.endSessionEndpoint) && MessagesPigeonInternal.deepEquals(lhs.pingEndIdpSessionEndpoint, rhs.pingEndIdpSessionEndpoint) && MessagesPigeonInternal.deepEquals(lhs.revocationEndpoint, rhs.revocationEndpoint)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OidcOpenIdConfigMessage")
    MessagesPigeonInternal.deepHash(value: authorizationEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tokenEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userinfoEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endSessionEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pingEndIdpSessionEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: revocationEndpoint, hasher: &hasher)
  }

  public var description: String {
    return "OidcOpenIdConfigMessage(authorizationEndpoint: \(String(describing: authorizationEndpoint)), tokenEndpoint: \(String(describing: tokenEndpoint)), userinfoEndpoint: \(String(describing: userinfoEndpoint)), endSessionEndpoint: \(String(describing: endSessionEndpoint)), pingEndIdpSessionEndpoint: \(String(describing: pingEndIdpSessionEndpoint)), revocationEndpoint: \(String(describing: revocationEndpoint)))"
  }
}

/// Flat, wire-serializable OIDC client configuration.
///
/// Neither [discoveryEndpoint] nor [openId] is required at the Pigeon-type
/// level — both native SDKs silently defer validation rather than throwing
/// if both are absent, so the bridge itself validates "at least one must be
/// present" in `OidcConfigParser` and throws a typed `OIDC_CONFIGURE_ERROR`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OidcConfigMessage: Hashable, CustomStringConvertible {
  /// The OAuth2/OIDC client id.
  var clientId: String
  /// The redirect URI registered for this client.
  var redirectUri: String
  /// The discovery endpoint URL, if discovery is used instead of an explicit [openId].
  var discoveryEndpoint: String? = nil
  /// The explicit OpenID endpoint configuration, if discovery is not used.
  var openId: OidcOpenIdConfigMessage? = nil
  /// OAuth2 scopes requested during authorization.
  var scopes: [String?]? = nil
  /// The `acr_values` authorization parameter.
  var acrValues: String? = nil
  /// Android-only at apply time — iOS's native `OidcClientConfig` has no
  /// such field.
  var signOutRedirectUri: String? = nil
  /// The `state` authorization parameter.
  var state: String? = nil
  /// The `nonce` authorization parameter.
  var nonce: String? = nil
  /// The `ui_locales` authorization parameter.
  var uiLocales: String? = nil
  /// Seconds. Named explicitly to avoid the Journey schema's units ambiguity.
  var refreshThresholdSeconds: Int64? = nil
  /// The `login_hint` authorization parameter.
  var loginHint: String? = nil
  /// The `display` authorization parameter.
  var display: String? = nil
  /// The `prompt` authorization parameter.
  var prompt: String? = nil
  /// Additional authorization parameters.
  var additionalParameters: [String?: String?]? = nil
  /// Whether to use Pushed Authorization Requests (RFC 9126).
  var par: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OidcConfigMessage? {
    let clientId = pigeonVar_list[0] as! String
    let redirectUri = pigeonVar_list[1] as! String
    let discoveryEndpoint: String? = nilOrValue(pigeonVar_list[2])
    let openId: OidcOpenIdConfigMessage? = nilOrValue(pigeonVar_list[3])
    let scopes: [String?]? = nilOrValue(pigeonVar_list[4])
    let acrValues: String? = nilOrValue(pigeonVar_list[5])
    let signOutRedirectUri: String? = nilOrValue(pigeonVar_list[6])
    let state: String? = nilOrValue(pigeonVar_list[7])
    let nonce: String? = nilOrValue(pigeonVar_list[8])
    let uiLocales: String? = nilOrValue(pigeonVar_list[9])
    let refreshThresholdSeconds: Int64? = nilOrValue(pigeonVar_list[10])
    let loginHint: String? = nilOrValue(pigeonVar_list[11])
    let display: String? = nilOrValue(pigeonVar_list[12])
    let prompt: String? = nilOrValue(pigeonVar_list[13])
    let additionalParameters: [String?: String?]? = nilOrValue(pigeonVar_list[14])
    let par = pigeonVar_list[15] as! Bool

    return OidcConfigMessage(
      clientId: clientId,
      redirectUri: redirectUri,
      discoveryEndpoint: discoveryEndpoint,
      openId: openId,
      scopes: scopes,
      acrValues: acrValues,
      signOutRedirectUri: signOutRedirectUri,
      state: state,
      nonce: nonce,
      uiLocales: uiLocales,
      refreshThresholdSeconds: refreshThresholdSeconds,
      loginHint: loginHint,
      display: display,
      prompt: prompt,
      additionalParameters: additionalParameters,
      par: par
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      redirectUri,
      discoveryEndpoint,
      openId,
      scopes,
      acrValues,
      signOutRedirectUri,
      state,
      nonce,
      uiLocales,
      refreshThresholdSeconds,
      loginHint,
      display,
      prompt,
      additionalParameters,
      par,
    ]
  }
  static func == (lhs: OidcConfigMessage, rhs: OidcConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.clientId, rhs.clientId) && MessagesPigeonInternal.deepEquals(lhs.redirectUri, rhs.redirectUri) && MessagesPigeonInternal.deepEquals(lhs.discoveryEndpoint, rhs.discoveryEndpoint) && MessagesPigeonInternal.deepEquals(lhs.openId, rhs.openId) && MessagesPigeonInternal.deepEquals(lhs.scopes, rhs.scopes) && MessagesPigeonInternal.deepEquals(lhs.acrValues, rhs.acrValues) && MessagesPigeonInternal.deepEquals(lhs.signOutRedirectUri, rhs.signOutRedirectUri) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.nonce, rhs.nonce) && MessagesPigeonInternal.deepEquals(lhs.uiLocales, rhs.uiLocales) && MessagesPigeonInternal.deepEquals(lhs.refreshThresholdSeconds, rhs.refreshThresholdSeconds) && MessagesPigeonInternal.deepEquals(lhs.loginHint, rhs.loginHint) && MessagesPigeonInternal.deepEquals(lhs.display, rhs.display) && MessagesPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && MessagesPigeonInternal.deepEquals(lhs.additionalParameters, rhs.additionalParameters) && MessagesPigeonInternal.deepEquals(lhs.par, rhs.par)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OidcConfigMessage")
    MessagesPigeonInternal.deepHash(value: clientId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: redirectUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: discoveryEndpoint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: openId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scopes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: acrValues, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: signOutRedirectUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nonce, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uiLocales, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: refreshThresholdSeconds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: loginHint, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: display, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: additionalParameters, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: par, hasher: &hasher)
  }

  public var description: String {
    return "OidcConfigMessage(clientId: \(String(describing: clientId)), redirectUri: \(String(describing: redirectUri)), discoveryEndpoint: \(String(describing: discoveryEndpoint)), openId: \(String(describing: openId)), scopes: \(String(describing: scopes)), acrValues: \(String(describing: acrValues)), signOutRedirectUri: \(String(describing: signOutRedirectUri)), state: \(String(describing: state)), nonce: \(String(describing: nonce)), uiLocales: \(String(describing: uiLocales)), refreshThresholdSeconds: \(String(describing: refreshThresholdSeconds)), loginHint: \(String(describing: loginHint)), display: \(String(describing: display)), prompt: \(String(describing: prompt)), additionalParameters: \(String(describing: additionalParameters)), par: \(String(describing: par)))"
  }
}

/// iOS-only browser presentation knobs. Android ignores every field here —
/// it only has Chrome Custom Tabs, no `BrowserType`/`BrowserMode` equivalent.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BrowserOptionsMessage: Hashable, CustomStringConvertible {
  /// One of `authSession` / `ephemeralAuthSession` (both implemented on iOS
  /// at 2.1.0). `nativeBrowserApp` / `sfViewController` are declared but not
  /// implemented natively — the iOS bridge rejects them rather than passing
  /// through to a silent no-op.
  var browserType: String? = nil
  /// One of `login` / `logout` / `custom`.
  var browserMode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BrowserOptionsMessage? {
    let browserType: String? = nilOrValue(pigeonVar_list[0])
    let browserMode: String? = nilOrValue(pigeonVar_list[1])

    return BrowserOptionsMessage(
      browserType: browserType,
      browserMode: browserMode
    )
  }
  func toList() -> [Any?] {
    return [
      browserType,
      browserMode,
    ]
  }
  static func == (lhs: BrowserOptionsMessage, rhs: BrowserOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.browserType, rhs.browserType) && MessagesPigeonInternal.deepEquals(lhs.browserMode, rhs.browserMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BrowserOptionsMessage")
    MessagesPigeonInternal.deepHash(value: browserType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: browserMode, hasher: &hasher)
  }

  public var description: String {
    return "BrowserOptionsMessage(browserType: \(String(describing: browserType)), browserMode: \(String(describing: browserMode)))"
  }
}

/// A minted OIDC token set. Deliberately excludes the expiry-stamp field
/// (`expireAt` on Android vs `expiresAt` on iOS diverge in both name and
/// visibility) — only `expiresIn` (present, public, on both) crosses the
/// bridge.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TokenMessage: Hashable, CustomStringConvertible {
  /// The OAuth access token.
  var accessToken: String
  /// The OAuth token type (e.g. `Bearer`), if the server returned one.
  var tokenType: String? = nil
  /// The granted scope string, if the server returned one.
  var scope: String? = nil
  /// The number of seconds until [accessToken] expires.
  var expiresIn: Int64
  /// The OAuth refresh token, if the server returned one.
  var refreshToken: String? = nil
  /// The OIDC ID token, if the server returned one.
  var idToken: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenMessage? {
    let accessToken = pigeonVar_list[0] as! String
    let tokenType: String? = nilOrValue(pigeonVar_list[1])
    let scope: String? = nilOrValue(pigeonVar_list[2])
    let expiresIn = pigeonVar_list[3] as! Int64
    let refreshToken: String? = nilOrValue(pigeonVar_list[4])
    let idToken: String? = nilOrValue(pigeonVar_list[5])

    return TokenMessage(
      accessToken: accessToken,
      tokenType: tokenType,
      scope: scope,
      expiresIn: expiresIn,
      refreshToken: refreshToken,
      idToken: idToken
    )
  }
  func toList() -> [Any?] {
    return [
      accessToken,
      tokenType,
      scope,
      expiresIn,
      refreshToken,
      idToken,
    ]
  }
  static func == (lhs: TokenMessage, rhs: TokenMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.accessToken, rhs.accessToken) && MessagesPigeonInternal.deepEquals(lhs.tokenType, rhs.tokenType) && MessagesPigeonInternal.deepEquals(lhs.scope, rhs.scope) && MessagesPigeonInternal.deepEquals(lhs.expiresIn, rhs.expiresIn) && MessagesPigeonInternal.deepEquals(lhs.refreshToken, rhs.refreshToken) && MessagesPigeonInternal.deepEquals(lhs.idToken, rhs.idToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TokenMessage")
    MessagesPigeonInternal.deepHash(value: accessToken, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tokenType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scope, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expiresIn, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: refreshToken, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: idToken, hasher: &hasher)
  }

  public var description: String {
    return "TokenMessage(accessToken: \(String(describing: accessToken)), tokenType: \(String(describing: tokenType)), scope: \(String(describing: scope)), expiresIn: \(String(describing: expiresIn)), refreshToken: \(String(describing: refreshToken)), idToken: \(String(describing: idToken)))"
  }
}

/// No authorization code, no `state`, no redirect URI ever crosses the
/// bridge — the native SDK captures the redirect and exchanges the code
/// internally on both platforms.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthorizeResultMessage: Hashable, CustomStringConvertible {
  /// Whether the browser flow completed successfully or was cancelled by the user.
  var type: AuthorizeResultType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthorizeResultMessage? {
    let type = pigeonVar_list[0] as! AuthorizeResultType

    return AuthorizeResultMessage(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: AuthorizeResultMessage, rhs: AuthorizeResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthorizeResultMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
  }

  public var description: String {
    return "AuthorizeResultMessage(type: \(String(describing: type)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AuthorizeResultType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return OidcOpenIdConfigMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return OidcConfigMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return BrowserOptionsMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return TokenMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return AuthorizeResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthorizeResultType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? OidcOpenIdConfigMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? OidcConfigMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? BrowserOptionsMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? TokenMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? AuthorizeResultMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PingOidcHostApi {
  /// Builds a native `OidcClient` for [config] and returns its handle id.
  func configureOidc(config: OidcConfigMessage, completion: @escaping (Result<String, Error>) -> Void)
  /// Builds a browser-capable `OidcWebClient` from the client identified by [clientId] and
  /// returns its handle id.
  func createWebClient(clientId: String, options: BrowserOptionsMessage?, completion: @escaping (Result<String, Error>) -> Void)
  /// Opens the system browser for the user to authenticate.
  func authorize(webClientId: String, completion: @escaping (Result<AuthorizeResultMessage, Error>) -> Void)
  /// Whether a signed-in user session already exists for this web client.
  func hasUser(webClientId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// The token most recently issued for this web client.
  func token(webClientId: String, completion: @escaping (Result<TokenMessage, Error>) -> Void)
  /// Forces a token refresh via the stored refresh token.
  func refresh(webClientId: String, completion: @escaping (Result<TokenMessage, Error>) -> Void)
  /// Fetches the userinfo claims for the signed-in user.
  func userInfo(webClientId: String, cache: Bool, completion: @escaping (Result<[String?: Any?], Error>) -> Void)
  /// Revokes the current token.
  func revoke(webClientId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Signs the user out.
  func signOff(webClientId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Releases the native resources backing [handleId] (either a client or web-client handle).
  func dispose(handleId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PingOidcHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PingOidcHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PingOidcHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Builds a native `OidcClient` for [config] and returns its handle id.
    let configureOidcChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.configureOidc\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureOidcChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! OidcConfigMessage
        api.configureOidc(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureOidcChannel.setMessageHandler(nil)
    }
    /// Builds a browser-capable `OidcWebClient` from the client identified by [clientId] and
    /// returns its handle id.
    let createWebClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.createWebClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createWebClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! String
        let optionsArg: BrowserOptionsMessage? = nilOrValue(args[1])
        api.createWebClient(clientId: clientIdArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createWebClientChannel.setMessageHandler(nil)
    }
    /// Opens the system browser for the user to authenticate.
    let authorizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.authorize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        api.authorize(webClientId: webClientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeChannel.setMessageHandler(nil)
    }
    /// Whether a signed-in user session already exists for this web client.
    let hasUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.hasUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasUserChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        api.hasUser(webClientId: webClientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hasUserChannel.setMessageHandler(nil)
    }
    /// The token most recently issued for this web client.
    let tokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.token\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      tokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        api.token(webClientId: webClientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      tokenChannel.setMessageHandler(nil)
    }
    /// Forces a token refresh via the stored refresh token.
    let refreshChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.refresh\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        api.refresh(webClientId: webClientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshChannel.setMessageHandler(nil)
    }
    /// Fetches the userinfo claims for the signed-in user.
    let userInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.userInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      userInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        let cacheArg = args[1] as! Bool
        api.userInfo(webClientId: webClientIdArg, cache: cacheArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      userInfoChannel.setMessageHandler(nil)
    }
    /// Revokes the current token.
    let revokeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.revoke\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      revokeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        api.revoke(webClientId: webClientIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      revokeChannel.setMessageHandler(nil)
    }
    /// Signs the user out.
    let signOffChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.signOff\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signOffChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let webClientIdArg = args[0] as! String
        api.signOff(webClientId: webClientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signOffChannel.setMessageHandler(nil)
    }
    /// Releases the native resources backing [handleId] (either a client or web-client handle).
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleIdArg = args[0] as! String
        api.dispose(handleId: handleIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
