// Copyright (c) 2026 Ping Identity Corporation. All rights reserved.
//
// This software may be modified and distributed under the terms
// of the MIT license. See the LICENSE file for details.
// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.pingidentity.flutter.oidc

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class AuthorizeResultType(val raw: Int) {
  /** The user completed the browser login flow successfully. */
  SUCCESS(0),
  /** The user dismissed the browser without completing login. Not an error. */
  CANCEL(1);

  companion object {
    fun ofRaw(raw: Int): AuthorizeResultType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Explicit OpenID endpoint configuration — the "skip discovery" escape
 * hatch. Mirrors ping_core's `OidcOpenIdConfig` field-for-field.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OidcOpenIdConfigMessage (
  /** The authorization endpoint URL. */
  val authorizationEndpoint: String,
  /** The token endpoint URL. */
  val tokenEndpoint: String,
  /** The userinfo endpoint URL. */
  val userinfoEndpoint: String,
  /** The end-session endpoint URL, if the provider supports RP-initiated logout. */
  val endSessionEndpoint: String? = null,
  /** The Ping end-IDP-session endpoint URL, using just the id token. */
  val pingEndIdpSessionEndpoint: String? = null,
  /** The token revocation endpoint URL. */
  val revocationEndpoint: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OidcOpenIdConfigMessage {
      val authorizationEndpoint = pigeonVar_list[0] as String
      val tokenEndpoint = pigeonVar_list[1] as String
      val userinfoEndpoint = pigeonVar_list[2] as String
      val endSessionEndpoint = pigeonVar_list[3] as String?
      val pingEndIdpSessionEndpoint = pigeonVar_list[4] as String?
      val revocationEndpoint = pigeonVar_list[5] as String?
      return OidcOpenIdConfigMessage(authorizationEndpoint, tokenEndpoint, userinfoEndpoint, endSessionEndpoint, pingEndIdpSessionEndpoint, revocationEndpoint)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      authorizationEndpoint,
      tokenEndpoint,
      userinfoEndpoint,
      endSessionEndpoint,
      pingEndIdpSessionEndpoint,
      revocationEndpoint,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OidcOpenIdConfigMessage
    return MessagesPigeonUtils.deepEquals(this.authorizationEndpoint, other.authorizationEndpoint) && MessagesPigeonUtils.deepEquals(this.tokenEndpoint, other.tokenEndpoint) && MessagesPigeonUtils.deepEquals(this.userinfoEndpoint, other.userinfoEndpoint) && MessagesPigeonUtils.deepEquals(this.endSessionEndpoint, other.endSessionEndpoint) && MessagesPigeonUtils.deepEquals(this.pingEndIdpSessionEndpoint, other.pingEndIdpSessionEndpoint) && MessagesPigeonUtils.deepEquals(this.revocationEndpoint, other.revocationEndpoint)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authorizationEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tokenEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userinfoEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endSessionEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pingEndIdpSessionEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.revocationEndpoint)
    return result
  }
  override fun toString(): String {
    return "OidcOpenIdConfigMessage(authorizationEndpoint=$authorizationEndpoint, tokenEndpoint=$tokenEndpoint, userinfoEndpoint=$userinfoEndpoint, endSessionEndpoint=$endSessionEndpoint, pingEndIdpSessionEndpoint=$pingEndIdpSessionEndpoint, revocationEndpoint=$revocationEndpoint)"
  }
}

/**
 * Flat, wire-serializable OIDC client configuration.
 *
 * Neither [discoveryEndpoint] nor [openId] is required at the Pigeon-type
 * level — both native SDKs silently defer validation rather than throwing
 * if both are absent, so the bridge itself validates "at least one must be
 * present" in `OidcConfigParser` and throws a typed `OIDC_CONFIGURE_ERROR`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OidcConfigMessage (
  /** The OAuth2/OIDC client id. */
  val clientId: String,
  /** The redirect URI registered for this client. */
  val redirectUri: String,
  /** The discovery endpoint URL, if discovery is used instead of an explicit [openId]. */
  val discoveryEndpoint: String? = null,
  /** The explicit OpenID endpoint configuration, if discovery is not used. */
  val openId: OidcOpenIdConfigMessage? = null,
  /** OAuth2 scopes requested during authorization. */
  val scopes: List<String?>? = null,
  /** The `acr_values` authorization parameter. */
  val acrValues: String? = null,
  /**
   * Android-only at apply time — iOS's native `OidcClientConfig` has no
   * such field.
   */
  val signOutRedirectUri: String? = null,
  /** The `state` authorization parameter. */
  val state: String? = null,
  /** The `nonce` authorization parameter. */
  val nonce: String? = null,
  /** The `ui_locales` authorization parameter. */
  val uiLocales: String? = null,
  /** Seconds. Named explicitly to avoid the Journey schema's units ambiguity. */
  val refreshThresholdSeconds: Long? = null,
  /** The `login_hint` authorization parameter. */
  val loginHint: String? = null,
  /** The `display` authorization parameter. */
  val display: String? = null,
  /** The `prompt` authorization parameter. */
  val prompt: String? = null,
  /** Additional authorization parameters. */
  val additionalParameters: Map<String?, String?>? = null,
  /** Whether to use Pushed Authorization Requests (RFC 9126). */
  val par: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OidcConfigMessage {
      val clientId = pigeonVar_list[0] as String
      val redirectUri = pigeonVar_list[1] as String
      val discoveryEndpoint = pigeonVar_list[2] as String?
      val openId = pigeonVar_list[3] as OidcOpenIdConfigMessage?
      val scopes = pigeonVar_list[4] as List<String?>?
      val acrValues = pigeonVar_list[5] as String?
      val signOutRedirectUri = pigeonVar_list[6] as String?
      val state = pigeonVar_list[7] as String?
      val nonce = pigeonVar_list[8] as String?
      val uiLocales = pigeonVar_list[9] as String?
      val refreshThresholdSeconds = pigeonVar_list[10] as Long?
      val loginHint = pigeonVar_list[11] as String?
      val display = pigeonVar_list[12] as String?
      val prompt = pigeonVar_list[13] as String?
      val additionalParameters = pigeonVar_list[14] as Map<String?, String?>?
      val par = pigeonVar_list[15] as Boolean
      return OidcConfigMessage(clientId, redirectUri, discoveryEndpoint, openId, scopes, acrValues, signOutRedirectUri, state, nonce, uiLocales, refreshThresholdSeconds, loginHint, display, prompt, additionalParameters, par)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      redirectUri,
      discoveryEndpoint,
      openId,
      scopes,
      acrValues,
      signOutRedirectUri,
      state,
      nonce,
      uiLocales,
      refreshThresholdSeconds,
      loginHint,
      display,
      prompt,
      additionalParameters,
      par,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OidcConfigMessage
    return MessagesPigeonUtils.deepEquals(this.clientId, other.clientId) && MessagesPigeonUtils.deepEquals(this.redirectUri, other.redirectUri) && MessagesPigeonUtils.deepEquals(this.discoveryEndpoint, other.discoveryEndpoint) && MessagesPigeonUtils.deepEquals(this.openId, other.openId) && MessagesPigeonUtils.deepEquals(this.scopes, other.scopes) && MessagesPigeonUtils.deepEquals(this.acrValues, other.acrValues) && MessagesPigeonUtils.deepEquals(this.signOutRedirectUri, other.signOutRedirectUri) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.nonce, other.nonce) && MessagesPigeonUtils.deepEquals(this.uiLocales, other.uiLocales) && MessagesPigeonUtils.deepEquals(this.refreshThresholdSeconds, other.refreshThresholdSeconds) && MessagesPigeonUtils.deepEquals(this.loginHint, other.loginHint) && MessagesPigeonUtils.deepEquals(this.display, other.display) && MessagesPigeonUtils.deepEquals(this.prompt, other.prompt) && MessagesPigeonUtils.deepEquals(this.additionalParameters, other.additionalParameters) && MessagesPigeonUtils.deepEquals(this.par, other.par)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.redirectUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.discoveryEndpoint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.openId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scopes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.acrValues)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.signOutRedirectUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nonce)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uiLocales)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.refreshThresholdSeconds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.loginHint)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.display)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.prompt)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.additionalParameters)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.par)
    return result
  }
  override fun toString(): String {
    return "OidcConfigMessage(clientId=$clientId, redirectUri=$redirectUri, discoveryEndpoint=$discoveryEndpoint, openId=$openId, scopes=$scopes, acrValues=$acrValues, signOutRedirectUri=$signOutRedirectUri, state=$state, nonce=$nonce, uiLocales=$uiLocales, refreshThresholdSeconds=$refreshThresholdSeconds, loginHint=$loginHint, display=$display, prompt=$prompt, additionalParameters=$additionalParameters, par=$par)"
  }
}

/**
 * iOS-only browser presentation knobs. Android ignores every field here —
 * it only has Chrome Custom Tabs, no `BrowserType`/`BrowserMode` equivalent.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BrowserOptionsMessage (
  /**
   * One of `authSession` / `ephemeralAuthSession` (both implemented on iOS
   * at 2.1.0). `nativeBrowserApp` / `sfViewController` are declared but not
   * implemented natively — the iOS bridge rejects them rather than passing
   * through to a silent no-op.
   */
  val browserType: String? = null,
  /** One of `login` / `logout` / `custom`. */
  val browserMode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrowserOptionsMessage {
      val browserType = pigeonVar_list[0] as String?
      val browserMode = pigeonVar_list[1] as String?
      return BrowserOptionsMessage(browserType, browserMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      browserType,
      browserMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BrowserOptionsMessage
    return MessagesPigeonUtils.deepEquals(this.browserType, other.browserType) && MessagesPigeonUtils.deepEquals(this.browserMode, other.browserMode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.browserType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.browserMode)
    return result
  }
  override fun toString(): String {
    return "BrowserOptionsMessage(browserType=$browserType, browserMode=$browserMode)"
  }
}

/**
 * A minted OIDC token set. Deliberately excludes the expiry-stamp field
 * (`expireAt` on Android vs `expiresAt` on iOS diverge in both name and
 * visibility) — only `expiresIn` (present, public, on both) crosses the
 * bridge.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TokenMessage (
  /** The OAuth access token. */
  val accessToken: String,
  /** The OAuth token type (e.g. `Bearer`), if the server returned one. */
  val tokenType: String? = null,
  /** The granted scope string, if the server returned one. */
  val scope: String? = null,
  /** The number of seconds until [accessToken] expires. */
  val expiresIn: Long,
  /** The OAuth refresh token, if the server returned one. */
  val refreshToken: String? = null,
  /** The OIDC ID token, if the server returned one. */
  val idToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TokenMessage {
      val accessToken = pigeonVar_list[0] as String
      val tokenType = pigeonVar_list[1] as String?
      val scope = pigeonVar_list[2] as String?
      val expiresIn = pigeonVar_list[3] as Long
      val refreshToken = pigeonVar_list[4] as String?
      val idToken = pigeonVar_list[5] as String?
      return TokenMessage(accessToken, tokenType, scope, expiresIn, refreshToken, idToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessToken,
      tokenType,
      scope,
      expiresIn,
      refreshToken,
      idToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TokenMessage
    return MessagesPigeonUtils.deepEquals(this.accessToken, other.accessToken) && MessagesPigeonUtils.deepEquals(this.tokenType, other.tokenType) && MessagesPigeonUtils.deepEquals(this.scope, other.scope) && MessagesPigeonUtils.deepEquals(this.expiresIn, other.expiresIn) && MessagesPigeonUtils.deepEquals(this.refreshToken, other.refreshToken) && MessagesPigeonUtils.deepEquals(this.idToken, other.idToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tokenType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scope)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.expiresIn)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.refreshToken)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.idToken)
    return result
  }
  override fun toString(): String {
    return "TokenMessage(accessToken=$accessToken, tokenType=$tokenType, scope=$scope, expiresIn=$expiresIn, refreshToken=$refreshToken, idToken=$idToken)"
  }
}

/**
 * No authorization code, no `state`, no redirect URI ever crosses the
 * bridge — the native SDK captures the redirect and exchanges the code
 * internally on both platforms.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthorizeResultMessage (
  /** Whether the browser flow completed successfully or was cancelled by the user. */
  val type: AuthorizeResultType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthorizeResultMessage {
      val type = pigeonVar_list[0] as AuthorizeResultType
      return AuthorizeResultMessage(type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthorizeResultMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    return result
  }
  override fun toString(): String {
    return "AuthorizeResultMessage(type=$type)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AuthorizeResultType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OidcOpenIdConfigMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OidcConfigMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrowserOptionsMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthorizeResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AuthorizeResultType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is OidcOpenIdConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is OidcConfigMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BrowserOptionsMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TokenMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is AuthorizeResultMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PingOidcHostApi {
  /** Builds a native `OidcClient` for [config] and returns its handle id. */
  fun configureOidc(config: OidcConfigMessage, callback: (Result<String>) -> Unit)
  /**
   * Builds a browser-capable `OidcWebClient` from the client identified by [clientId] and
   * returns its handle id.
   */
  fun createWebClient(clientId: String, options: BrowserOptionsMessage?, callback: (Result<String>) -> Unit)
  /** Opens the system browser for the user to authenticate. */
  fun authorize(webClientId: String, callback: (Result<AuthorizeResultMessage>) -> Unit)
  /** Whether a signed-in user session already exists for this web client. */
  fun hasUser(webClientId: String, callback: (Result<Boolean>) -> Unit)
  /** The token most recently issued for this web client. */
  fun token(webClientId: String, callback: (Result<TokenMessage>) -> Unit)
  /** Forces a token refresh via the stored refresh token. */
  fun refresh(webClientId: String, callback: (Result<TokenMessage>) -> Unit)
  /** Fetches the userinfo claims for the signed-in user. */
  fun userInfo(webClientId: String, cache: Boolean, callback: (Result<Map<String?, Any?>>) -> Unit)
  /** Revokes the current token. */
  fun revoke(webClientId: String, callback: (Result<Unit>) -> Unit)
  /** Signs the user out. */
  fun signOff(webClientId: String, callback: (Result<Boolean>) -> Unit)
  /** Releases the native resources backing [handleId] (either a client or web-client handle). */
  fun dispose(handleId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by PingOidcHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PingOidcHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PingOidcHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.configureOidc$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as OidcConfigMessage
            api.configureOidc(configArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.createWebClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as String
            val optionsArg = args[1] as BrowserOptionsMessage?
            api.createWebClient(clientIdArg, optionsArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.authorize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            api.authorize(webClientIdArg) { result: Result<AuthorizeResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.hasUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            api.hasUser(webClientIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.token$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            api.token(webClientIdArg) { result: Result<TokenMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.refresh$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            api.refresh(webClientIdArg) { result: Result<TokenMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.userInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            val cacheArg = args[1] as Boolean
            api.userInfo(webClientIdArg, cacheArg) { result: Result<Map<String?, Any?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.revoke$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            api.revoke(webClientIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.signOff$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val webClientIdArg = args[0] as String
            api.signOff(webClientIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ping_oidc.PingOidcHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleIdArg = args[0] as String
            api.dispose(handleIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
